### PR TITLE
Updated the index css file #40226

### PR DESCRIPTION
**Pull request by sidram05**
…ution in Technical documentation

#### Pre-Submission Checklist

- [x] Your pull request targets the `master` branch of freeCodeCamp/testable-projects-fcc
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] Your changes have been tested either locally or using a newly created CDN based on your fork's testable-projects-fcc/build/bundle.js file

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.

- [x] Closes currently open issue: Closes #XXX

### CODE REVIEW

**Comment by RandellDawson** [comment]
@ojeytonwilliams What is causing this to fail Travis?

**Comment by nhcarrigan** [comment]
@RandellDawson it *looks* like there is an issue with the way the `commit` is formatted.

@sidram05 could you walk me through how you committed the changes? Did you use `commitizen`?

**Comment by sidram05** [comment]
Hi @nhcarrigan I used github desktop to commit the changes

**Comment by nhcarrigan** [comment]
The CI on this repository specifically looks for the structure that commitizen applies, I believe.

**Comment by nhcarrigan** [comment]
Linked to issue: https://github.com/freeCodeCamp/freeCodeCamp/issues/40226

**Comment by lasjorg** [comment]
@sidram05 You have to do the commit again. If you run `yarn commit` or `npm run commit` it will guide you through it.

The commit message has to follow the convention `subject(scope[optional]): tense commit message`

So for example `fix: change white-space to pre-line`

**Comment by sidram05** [comment]
> @sidram05 You have to do the commit again. If you run `yarn commit` or `npm run commit` it will guide you through it.
> 
> The commit message has to follow the convention `subject(scope[optional]): tense commit message`
> 
> So for example `fix: change white-space to pre-line`

Hi @lasjorg, i did give it a try but seeing the following error message 

git-cz-error

**Comment by lasjorg** [comment]
@sidram05 Did you install all the dependencies? That is, did you run `yarn install`?

**Comment by ojeytonwilliams** [comment]
Sorry for the delay, I missed this notification.  I agree with the consensus here - @sidram05 if you're having problems when you run `yarn install` I recommend reaching out on [Discord](https://discord.com/invite/pFspAhS)

**Comment by lasjorg** [comment]
Closed, new PR in #1250

**Pull request closed without merging**
