### PR TITLE
fix: fcc-test-ui may be positioned incorrectly

### PR DESCRIPTION
**Pull request by ValeraS**
#### Pre-Submission Checklist

- [x] Your pull request targets the `master` branch of freeCodeCamp/testable-projects-fcc
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] Your changes have been tested either locally or using a newly created CDN based on your fork's testable-projects-fcc/build/bundle.js file
- [x] Working changes have been added to the build by running `npm run build`

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.

- [ ] Closes currently open issue: Closes #XXX

#### Description

Example of an incorrect position in Chrome:
https://codepen.io/freeCodeCamp/pen/qRZeGZ
image

### CODE REVIEW

**Comment by tbushman** [comment]
@ValeraS Is this a follow-up to #556 ? I haven't seen this particular problem before.

**Comment by ValeraS** [comment]
@tbushman No, it isn't. It works wrong now.

We have two problems:
1. Only on Chrome. Camper's Pen has a rule `div { position: relative; }` and we have a rule `div { position: static; }`. But our rule not influences on wrapper div because of ShadowDom. And we position our elements relative to the div, not the body.

2. The input element is fixed on the top left corner. When you scroll down you don't see it but can press on it.

**Comment by tbushman** [comment]
Yikes, sorry. LGTM! merging

**Comment by ValeraS** [comment]
@tbushman This fix is also buggy. Position `fixed` makes new stacking context, and the `z-index` used for children works only in this context. As a result, our UI can be located below the camper's elements.
Possible solution:
```
<div id="fcc_test_suite_wrapper" style="
    position: relative;
    z-index: 99999;
"></div>
```

**Comment by tbushman** [comment]
@ValeraS OK. Thanks for following up. I think we need a new PR. Will you be doing that?

**Pull request merged**
