### PR TITLE
feat: new survey form

### PR DESCRIPTION
**Pull request by lasjorg**
#### Pre-Submission Checklist

- [x] Your pull request targets the `master` branch of freeCodeCamp/testable-projects-fcc
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] Your changes have been tested either locally or using a newly created CDN based on your fork's testable-projects-fcc/build/bundle.js file

#### Type of Change

- [ ] Small bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
  
- [ ] Closes currently open issue: Closes https://github.com/freeCodeCamp/testable-projects-fcc/issues/983

#### Description

Here is my first go at the new survey form. Any corrections or suggestions are welcome.

### CODE REVIEW

**Comment by lasjorg** [comment]
@tbushman I forgot to @ you. When you have the time can you take a look at this.

**Comment by tbushman** [comment]
@lasjorg This works, is well organized, and is beautiful. In all, your changes make form requirements clear. Thanks.  
Since you are taking the time to update the project, does the background image have creative-commons licensing? Also, if you are not attached to it, it would be nice to use an image that better reflects fCC's student body diversity.   
Could you please share a link to a CodePen version or other running version so that @QuincyLarson can approve it?

**Comment by lasjorg** [comment]
@tbushman Yes, all Unsplash images are under an open [own license](https://unsplash.com/license) modeled on CC0. You can [read more here](https://help.unsplash.com/en/articles/2612312-how-is-the-unsplash-license-different-to-the-cc0-license) about the difference between the two licenses.

I actually started out looking for images with both gender, ethnicity, and age in mind. I had a hard time finding one that was good quality, would work as a background image, and that I knew for sure was under an open license. It quickly became a rabbit hole and I just stopped looking. I can just use a neutral image instead.

Here it is with a more neutral image. Which might actually be better as it is less attention-grabbing.
https://codepen.io/lasjorg/full/eYYzNGO

Here is the original for reference
https://codepen.io/lasjorg/full/bGGGEdy


Or, if you or anyone knows of a good image that I can use please let me know.

**Comment by tbushman** [comment]
@lasjorg The original is a nicer image. Thank you for looking. I would like to have at least one other moderator sign off on this example project update. @moderators

**Comment by scissorsneedfoodtoo** [comment]
@lasjorg, thank you for all your hard work updating this project. 

Glad to see that it's passing all the tests so we maintain backwards compatibility. I'm more partial to the original image, too, even if it's not the most diverse as @tbushman mentioned. We can always switch out the picture if we find a better one later, maybe even one from a freeCodeCamp study group or event?

As for next steps, I'll get the image into our CDN and comment here with the new URL. After that, we should be good to merge this.

**Comment by scissorsneedfoodtoo** [comment]
Here's the image for the survey from background: https://cdn.freecodecamp.org/testable-projects-fcc/images/survey-form-background.jpeg

Would you mind updating the URL here before we merge, @lasjorg?

**Comment by lasjorg** [comment]
@scissorsneedfoodtoo URL updated.

I wanted to use something like the [group image here](https://www.freecodecamp.org/news/about/). But it isn't that great quality and it has no attribution or license. I did try it out and it's pretty attention-grabbing so it doesn't work that great as a background.

I can keep playing around a bit with the background and see if I can come up with something. Again, if anyone has a good image just let me know.

**Comment by scissorsneedfoodtoo** [comment]
Okay, sounds good. I'll ask @QuincyLarson if he has or knows of a good image we might be able to use.

**Comment by QuincyLarson** [comment]
How about this image from freeCodeCamp Seoul? Nobody is facing the photo so I think it's a bit less distracting of a background. Photo by Sonya Moisset‎.
13244071_10156920293555494_8209004573823642463_o

**Comment by lasjorg** [comment]
@QuincyLarson  Thank you. That image works well I think. 

Here is a Codepen with that image as the background.
https://codepen.io/lasjorg/full/BaaLEEL

And just for good measure, here is it with a few corrections to the image. Most you totally can't see because of the overlay. It's mainly that I wanted to blur the brick wall a bit.
https://codepen.io/lasjorg/full/mddrZML

Here is the link to the corrected image just in case.
https://raw.githubusercontent.com/lasjorg/fcc-form-example-image/master/67103817-7c51e200-f18b-11e9-975f-f74561336a9a-lj.jpg


If everybody likes it can @scissorsneedfoodtoo upload it to the CDN?

**Comment by scissorsneedfoodtoo** [comment]
Thank you for the fCC Seoul image @QuincyLarson. Looks great in @lasjorg's updated examples.

The new image is at the [same address](https://cdn.freecodecamp.org/testable-projects-fcc/images/survey-form-background.jpeg), so this should be ready to merge as-is.

Thank you for all your hard work here, @lasjorg! Excited to see this live :+1: :+1: Also, thank you @tbushman for your review.

**Comment by scissorsneedfoodtoo** [comment]
Just updated the survey form example project with your [second example}(https://codepen.io/lasjorg/full/mddrZML) that blurs the brick wall a bit. Check it out here: https://codepen.io/freeCodeCamp/pen/VPaoNP

**Comment by lasjorg** [comment]
@scissorsneedfoodtoo Thanks for the merge.

I'd also just like to give my thanks to @tbushman for the review and @QuincyLarson for the image.

And I do hope it's OK we used an edited version of the original image, if not just let me know.

**Comment by scissorsneedfoodtoo** [comment]
@lasjorg, no problem. Thank you for all of your hard work updating these projects.

I'm sure using a slightly edited version of the image is fine. If not, I can quickly switch it out for the original in the CDN.

**Pull request merged**
