### PR TITLE
Drum Machine: mousedown-click-mouseup and audio element paused Object.properties

### LINKED ISSUE #307: [BETA] Build a Drum Machine Tests 5-7 Not Passing (possible React issue)
#### Issue Description
The last three tests aren't passing for me (5 - click to play a sound, 6 - press a key to play a sound, 7 - the #display element displays a string name for the sound), even though all three things are happening.

I checked the ["bundle.js"](https://gitcdn.link/cdn/freeCodeCamp/testable-projects-fcc/db389c49dd321d8fc6d34fcad29c28d1d969c6f9/build/bundle.js) file, and the relevant code from the 5th test (click to play) is:
```
reqNum++;
it(reqNum + '. When I click on a .drum-pad element, the audio clip\n      contained in its child <audio> element should be triggered.', function () {
	_chai.assert.isAtLeast(audioElements.length, 9, 'Audio elements do not exist ');
	audioElements.forEach(function (el) {
		document.getElementById(el.parentElement.id).click();
		_chai.assert.isNotOk(document.getElementById(el.id).paused, 'The <audio> element with id="' + el.id + '" does not play when the ' + el.id + ' .drum-pad is clicked ');
	});
});
```
To explain *why I believe* it is failing, a brief explanation of my program logic:

I built my Drum Machine with React, using Stateless Functional Components for everything but the highest-level container. I had to resort to using three global-context arrays, one for the keys in order, and two others in parallel order for the two soundbanks.

5. I handle clicks via "MouseDown" events that allow the button to be re-classed so it lights up, and subsequent "MouseUp" events that reset the Container component's state. The event handlers are defined at the top-level Container component, and passed in as props through this branch of my component tree:
```
<Container />
  <PadBank />
    <Button />
      <div className="button" onMouseDown="..." onMouseUp="...">
```
So, the buttons don't have a click event, so this may be why it's failing. 

6. Also, looking at the next codeblock in "bundle.js", I noticed that the keydown event gets sent to the parent element of the audio clip. However, in the React lessons in the Beta, I noticed that in [the "add Event Listeners" lesson](https://beta.freecodecamp.org/en/challenges/react/add-event-listeners), `keydown` event listeners were added to the document. When I googled around, it seemed that I couldn't add keydown events to specific elements that weren't inputs or textareas (per stackoverflow), despite W3Schools' saying that `<div>`s weren't on the excluded list. So, i just followed the example in the curriculum, and it worked. I don't think this is a problem with my implementation, but of course I could be totally wrong.
```
reqNum++;
it(reqNum + '. When I press the trigger key associated with each\n      .drum-pad, the audio clip contained in its child <audio> element should be\n      triggered (e.g. pressing the Q key should trigger the drum pad which\n      contains the string "Q", pressing the W key should trigger the drum pad\n      which contains the string "W", etc.).', function () {
	this.timeout(900);
	var keyCodes = [81, 87, 69, 65, 83, 68, 90, 88, 67];
	_chai.assert.isAtLeast(audioElements.length, 9, 'Audio elements do not exist ');
	return new Promise(function (resolve) {
		setTimeout(function () {
			audioElements.forEach(function (el, i) {
				__triggerKeyboardEvent(document.getElementById(el.parentElement.id), keyCodes[i]);
				_chai.assert.isNotOk(document.getElementById(el.id).paused, 'No audio plays when the ' + el.id + ' key is pressed ');
			});
			resolve();
		}, 800);
	});
});
```

7. I looked at the code for the display string, but I think the issue is clicking vs mouseDown-ing again. I've reproduced it here:
```
reqNum++;
it(reqNum + '. When a .drum-pad is triggered, a string describing the\n      associated audio clip is displayed as the inner text of the #display\n      element (each string must be unique).', function () {
	this.timeout(900);
	var displayText = [];
	return new Promise(function (resolve, reject) {
		setTimeout(function () {
			drumPads.forEach(function (pad) {
				document.getElementById(pad.id).click();
				displayText.push(document.getElementById('display').innerText);
			});
			displayText = displayText.filter(function (str, i) {
				return displayText[0] === displayText[i];
			});
			if (displayText.length === 1) {
				resolve();
			} else {
				reject(new Error('Each time a drum pad is triggered, a unique string should ' + 'be displayed in the element with the id "display"'));
			}
		}, 800);
	});
});
```

#### Browser Information
* Browser Name, Version: Windows 10, 64-bit
* Operating System: Chrome 65.0.3325.181
* Mobile, Desktop, or Tablet: Desktop 

#### Your Code / Link to Your Pen
https://codepen.io/vipatron/full/wjzYJo/

### PR DESCRIPTION
**Pull request by tbushman**
#### Pre-Submission Checklist

- [x] Your pull request targets the `master` branch of freeCodeCamp/testable-projects-fcc
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] Your changes have been tested either locally or using a newly created CDN based on your fork's testable-projects-fcc/build/bundle.js file
- [x] Working changes have been added to the build by running `npm run build`

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.

- [x] Closes currently open issue: Closes #307

#### Description

This PR accommodates all click events with `mousedown`, `click`, and `mouseup` in that order. Additionally, dispatched events on DOM elements (`<audio>`) need to be configured with Object.defineProperties in a similar way to the workaround in markdown-previewer. Before all of the tests, we make the audio object configurable and writable.

### CODE REVIEW

**Comment by tbushman** [comment]
@tchaffee The tests fail while attempting to locate the bundle.js at localhost.daplie ... not sure if it's because of something in this PR... looking into...

**Comment by tchaffee** [comment]
@tbushman localhost.daplie started failing for me a couple of days ago too. I will look into it.

**Comment by tchaffee** [comment]
@tbushman I think we should fix issue #277 to get this to pass. What do you think?

**Comment by tbushman** [comment]
@tchaffee I'm able to get the old config running locally, but for our Travis tests, we could go with Saucelabs... It looks like Saucelabs would allow us to set up separate environment variables for local vs Travis bundle urls: https://docs.travis-ci.com/user/gui-and-headless-browsers/ . Is it ok if I sign us up and test that (which should allow us to keep more of our current setup, if I'm not mistaken)?

**Comment by tchaffee** [comment]
@tbushman you should be able to get the old config working on Travis too, without even using Saucelabs. Travis is running under Ubuntu if I remember right, so it's just a matter of adding the commands that will create the certs. If we decide to add more browsers to the mix we will eventually most likely have to add Saucelabs to the mix anyway, but for now it might be overkill and extra maintenance we don't need. BTW, can you create a PR for the old config if you got that working? I haven't had time.

**Comment by tbushman** [comment]
@tchaffee I got that working. Now, however, the pomodoro clock fails audio tests. I am opening a new PR with some of the fixes from this PR with shared modules for `<audio>` element configuration and event triggering in `utils/element-utils.js`. From what I'm reading, React's caching mechanisms prevent direct reading of `<audio>`.paused .

**Comment by tchaffee** [comment]
@tbushman I'm not sure what's needed as a next step here? Rebase? But let me know when it's ready again for review and I'll get to it as soon as I can.

**Comment by tbushman** [comment]
@tchaffee OK. Ready for review.

**Comment by tchaffee** [comment]
LGTM!

**Pull request merged**
