### PR TITLE
fix: change white-space to pre-line

### PR DESCRIPTION
**Pull request by sidram05**
#### Pre-Submission Checklist

- [x] Your pull request targets the `master` branch of freeCodeCamp/testable-projects-fcc
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] Your changes have been tested either locally or using a newly created CDN based on your fork's testable-projects-fcc/build/bundle.js file

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [x] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.

- [x] Closes currently open issue: Closes #XXX

### CODE REVIEW

**Comment by lasjorg** [comment]
LGTM :tada:

Thanks for fixing this issue @sidram05 and congratulations on your first contribution to this repo.

**Comment by lasjorg** [comment]
@moT01 Can you update the Codepen with this change?

https://codepen.io/freeCodeCamp/pen/NdrKKL?editors=1100

CSS Line 77:

From:

`white-space: pre;`

To:

`white-space: pre-line;`

---

Not sure who else has access to Codepen, other than you and @scissorsneedfoodtoo. I never got any login credentials for Codepen so I can't do it.

**Comment by moT01** [comment]
Done @lasjorg 👍

**Comment by lasjorg** [comment]
@moT01 Thank you!

**Pull request merged**
