### PR TITLE
bundle.js using the latest version of jquery and webpack per package.json versions.

### LINKED ISSUE #116: Upgrade bundle.js to use latest webpack and jquery
If you fork this project and run `npm install` you get newer versions of webpack and jquery (based on the required versions in `package.json`). Jquery goes from v3.1.1 to v3.2.1. 

This means running a build will result in many changes to the `bundle.js` file, which would not make sense to commit in a PR related to other issues, especially if this upgrade needed to be reversed for some reason.

The latest version of jquery says there are no breaking changes, but just to be sure every sample project on codepen should be tested with the new `bundle.js`

### PR DESCRIPTION
**Pull request by tchaffee**
#### Pre-Submission Checklist
- [x] Your pull request targets the `master` branch of freeCodeCamp/testable-projects-fcc
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] Your changes have been tested either locally or using a newly created CDN based on your fork's testable-projects-fcc/build/bundle.js file
- [x] Working changes have been added to the build by running `npm run build`

#### Type of Change

- [ ] Small bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue (replace XXX with an issue no): Closes #116 

#### Description
No code was changed. I just ran the build process after running `npm install`, which results in a newer version of jquery being used for the bundle. Every sample project was tested to make sure the new version of jquery doesn't break anything.

### CODE REVIEW

**Comment by tbushman** [comment]
@tchaffee This bundle.js works with all the FCC Codepens. This should probably be merged before any other PRs.

**Comment by tchaffee** [comment]
@tbushman Normally you can go ahead and do the merge yourself if you have reviewed it and you are happy with it. Since other PRs are waiting on this, I am going to merge it myself now. Thanks for the timely review!

**Comment by no-stack-dub-sack** [comment]
@tchaffee normally, I would prefer a secondary review and to have someone else merge the PR. On this project, I've been merging my own because I've been literally the only person (save a couple of PRs here and there from others) working on it. 

This is not a big one and I'm ok with this, but in the future, let's stick to the FCC model. 

At least one review, and a LGTM (looks good to me), the reviewer can merge.

Sorry for being late to the party, I'm still playing catch up just getting back from vacation.

**Comment by tbushman** [comment]
Thanks Peter. This merge was in order to rebase and I reviewed it. We are
holding all other pull requests. Thanks!

**Comment by tchaffee** [comment]
@no-stack-dub-sack makes sense. That's normally what I would do. Per the comment thread above this was already reviewed as ok and I only merged it myself because it was holding up other PRs.

**Pull request merged**
