### PR TITLE
fix: flaky random quote machine test

### PR DESCRIPTION
**Pull request by scissorsneedfoodtoo**
#### Pre-Submission Checklist

- [x] Your pull request targets the `master` branch of freeCodeCamp/testable-projects-fcc
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] Your changes have been tested either locally or using a newly created CDN based on your fork's testable-projects-fcc/build/bundle.js file

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.

- [ ] Closes currently open issue: Closes #XXX

#### Description

This PR adjusts two tests for the Random Quote Machine project to account for situations where the same quote and/or author are shown multiple times in a row.

With these changes, if the quote text or quote author are the same as the one at the beginning of the test, the `new-quote` button is pressed about every second until a new quote or author are displayed.

### CODE REVIEW

**Comment by RandellDawson** [comment]
What will happen if the user only has one quote or 3 of the same quote in the project?

**Comment by scissorsneedfoodtoo** [comment]
Hey @RandellDawson. For projects like that, both the original tests and the updated tests would fail, so there's no real change in that regard.

These updates just try to get new quotes or authors if the one is shown twice in a row.

**Review by moT01 — CHANGES_REQUESTED** [review]
If I run this on a project that doesn't have a `#text` or `#author` element, the intervals never get cleared and I get an infinite loop of logs in my console. Perhaps we should clear it after or timeout, or make sure the element exists first?

Edit: Actually, I'm not sure if it's these tests specifically causing it, or it's another test - or both. Looking into it.

More Edit: Yea, seems like any of the tests with the interval are causing this. Looks like they were pre-existing. Do we want to take a look at that with this PR @scissorsneedfoodtoo?

**Comment by scissorsneedfoodtoo** [comment]
Nice catch with that @moT01, thanks for looking into it.

Even though it's a preexisting issue, it seems like a simple enough fix. I'll take a crack at it and let you know once it's ready to review.

**Comment by scissorsneedfoodtoo** [comment]
@moT01, thanks again for catching that infinite log loop issue. This should be ready for another round of review.

One way to test the last changes with this repo is to make sure `HEADLESS=0` is set in the `.env` file, and comment out `await driver.quit();` in `automate-utils.js` so the browser stays open after the tests run.

You can also comment out everything but the lines for the Random Quote machines tests in `src/project-tests/index.js` so you don't have to run all the other test suites.

**Review by moT01 — APPROVED** [review]
LGTM 🎉

**Pull request merged**
