### PR TITLE
Change Javascript to JavaScript to reflect changes on the monorepo

### PR DESCRIPTION
**Pull request by thecodingaviator**
#### Pre-Submission Checklist

- [x] Your pull request targets the `master` branch of freeCodeCamp/testable-projects-fcc
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [ ] Your changes have been tested either locally or using a newly created CDN based on your fork's testable-projects-fcc/build/bundle.js file
- [ ] Working changes have been added to the build by running `npm run build`

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [ ] Tested changes locally.

- [ ] Closes currently open issue: Closes #XXX

#### Description

This PR reflects changes made to the fCC page of these tests over here https://github.com/freeCodeCamp/freeCodeCamp/pull/35183/commits/a32f2da271c08b0d2b7c2b6abfbffbc865cd74b8

### CODE REVIEW

**Comment by thecodingaviator** [comment]
@tbushman I'm not sure what I'm missing over here. Why is Travis failing?

**Comment by tbushman** [comment]
@thecodingaviator I think this is a `commitlint` error. To run a git commit, use `yarn commit` and follow the cli instructions for forming a commit message. You may need to squash commits after to remove the error.

**Comment by thecodingaviator** [comment]
@tbushman I don't have `yarn` could you fix it for me please?

**Comment by thecodingaviator** [comment]
@tbushman I guess it's fixed now, I didn't have the `git-cz` package installed, that was causing npm committing problems

**Comment by tbushman** [comment]
LGTM thanks!

**Pull request merged**
