### PR TITLE
docs(readme): update documentations for new link

### PR DESCRIPTION
**Pull request by raisedadead**

### CODE REVIEW

**Comment by tchaffee** [comment]
This is blocked because it goes along with the reverted PR from @Bouncey . Waiting on that PR to be resubmitted so we can merge this one at the same time.

**Comment by tchaffee** [comment]
@Bouncey I'm ready to look at this and get it resolved. Is the old PR available somewhere so I can look at it and get it working? Might be my ignorance of github on how to go about this... Thanks.

**Comment by raisedadead** [comment]
https://github.com/freeCodeCamp/testable-projects-fcc/pulls?q=is%3Apr+is%3Aclosed+author%3ABouncey

**Comment by raisedadead** [comment]
Here you go: https://github.com/freeCodeCamp/testable-projects-fcc/pull/318

**Comment by tchaffee** [comment]
@raisedadead Is this ready to merge now? The production bundle is available at https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js going forward?

**Comment by raisedadead** [comment]
Yes that is correct.

**Comment by tchaffee** [comment]
Personal Portfolio keeps failing the tests for some reason. Strange because this is just a documentation change, so most likely unrelated. I will look into it and fix it.

**Comment by tchaffee** [comment]
I could not get the tests for this to pass. I even tried clearing Travis cache. Not sure what I'm missing, but since I can get tests to pass on new PR #439 with the same exact change I'm merging that one and closing this.

**Pull request closed without merging**
