### PR TITLE
using getBoundingClientRect instead of parsing transform attribute fo…

### LINKED ISSUE #528: D3 Bar Chart Axis-data alignment tests
#### Issue Description
Hello. Cant pass #Content tests 10 and 11. There seems to be a mistake in the example pen IMO (and thus maybe in tests). I think it is logical that ticks on x-axis represent the start of the corresponding year. But the last 3 arrays of provided json.data are for Q123 of 2015 and technically corresponding bars should be positioned to the right of 2015-year-tick. I`ve looked in the example pen code (sorry), and the problem seems to be that the json.data is first parsed into array of years only. So the domain for x-axis scale is from '1947' to '2015' and not from '1947-01-01' to '2015-07-01'.
Y-axis alignment test (11) is not passing either - i don`t know what is the problem-it looks the same as the example one.

#### Browser Information
desktop Firefox Dev. Ed., Chrome
Win 10
#### Your Code / Link to Your Pen
https://github.com/glushkov89/FCC-Bar-Chart

#### Screenshot
Example pen:
[](https://postimg.cc/image/chfkchxwn/)

My chart:
[](https://postimg.cc/image/4bxiefp47/)

JSON:
[](https://postimg.cc/image/pa3oc449z/)

### PR DESCRIPTION
**Pull request by tbushman**
…r shape and tick positions

#### Pre-Submission Checklist

- [x] Your pull request targets the `master` branch of freeCodeCamp/testable-projects-fcc
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] Your changes have been tested either locally or using a newly created CDN based on your fork's testable-projects-fcc/build/bundle.js file
- [x] Working changes have been added to the build by running `npm run build`

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.

- [x] Closes currently open issue: Closes #528

#### Description

This will help with cases where D3 margin conventions are not consistent.

### CODE REVIEW

**Comment by tbushman** [comment]
I need to update the accompanying tdd ... brb

**Comment by tchaffee** [comment]
@tbushman I'm assuming you no longer have a question for me? Checking just in case.

**Comment by tbushman** [comment]
@tchaffee Right. No further questions. Removing the blocked label.  
  
The other open D3 issues are non-related, but this would have helped in a few past cases I can think of, including #528 . Thanks in advance for a review.

**Comment by tbushman** [comment]
The reason the JSDOM tests worked previously is that getTickPosition used a tick's own transform attribute to determine position. With the introduction of the getBoundingClientRect() method, the JSDOM test DOM strings in `test/alignment-D3.js` are logging, for example, a shape position of `0` with surrounding tick positions `[0,0]`. I do not think the JSDOM module is actually spatializing DOM elements from our test DOM strings.

**Comment by tchaffee** [comment]
@tbushman You are right. Per the jsdom docs, no layout is performed. Which means that it's no longer the right tool for us to use for this testing. I've opened issue #550 to replace jsdom with Selenium. Once that is in place, we should be able to get your new tests to pass.

**Comment by tchaffee** [comment]
@tbushman I have a feeling I am not going to get to rewriting the tests to use Selenium for at least a couple of weeks. Tests are necessary work, but they are not meant to get in the way of our progress like this. If you can wait then I will eventually get to this. But if you would rather merge this, I don't have a problem with you temporarily removing the offending tests until I can re-write that test suite to use Selenium. Let me know your thoughts please.

**Comment by tbushman** [comment]
@tchaffee OK, yeah -- I'll remove the failing tests. Thanks.

**Comment by tbushman** [comment]
bbiab -- need to figure out how to amend an old commit message

**Comment by tchaffee** [comment]
@tbushman If it's not too much of a pain, could you create a separate PR that removes the failing tests and we can merge that first? It will allow me to later reverse the PR so I can get those tests back easily without undoing your work here.

**Comment by ValeraS** [comment]
@tbushman Do not forget to remove bundle.js. It's not needed in repo anymore.

**Comment by tbushman** [comment]
@ValeraS Such a relief. Thanks.

**Comment by tbushman** [comment]
@ValeraS I'm looking at fCC/CDN and I don't see it updating there. How can we know the CDN is updating?

**Comment by tbushman** [comment]
@tchaffee @ValeraS There's a discussion at https://github.com/travis-ci/travis-ci/issues/5518#issuecomment-175841782 about `skip-cleanup` for node_modules  

I also wonder if `commit -m` in `deploy.sh` will still work with commitizen in place.

**Comment by tbushman** [comment]
Possibly related: https://github.com/travis-ci/dpl/issues/353 --- Windows newlines

**Comment by tchaffee** [comment]
@ValeraS @tbushman Sorry for my delayed involvement - I have had other pressing matters on other projects that I have to deal with. I should be able to put in some more effort and get back to this sometime next week.

**Comment by tchaffee** [comment]
@tbushman @ValeraS What's the status with this? Can I merge it? Or are we still waiting on something? If my help is needed I can set aside time today and tomorrow.

**Comment by tbushman** [comment]
@tchaffee Yes, please merge.

**Comment by tchaffee** [comment]
Just to leave no doubt, I reviewed this code previously and LGTM.

**Pull request merged**
