### PR TITLE
Feature/treemap

### PR DESCRIPTION
**Pull request by paycoguy**

### CODE REVIEW

**Comment by paycoguy** [comment]
@no-stack-dub-sack I just squashed the commits.  

The codepen link to the example project is:

http://codepen.io/paycoguy/pen/JERVGa

Here are the links to the datasets (in case you want to host them elsewhere)

https://rawgit.com/paycoguy/FCC-example-projects/master/tree-map/data/video_game_sales.json
https://rawgit.com/paycoguy/FCC-example-projects/master/tree-map/data/movies.json
https://rawgit.com/paycoguy/FCC-example-projects/master/tree-map/data/kickstarter.json

**Comment by no-stack-dub-sack** [comment]
@paycoguy awesome! thanks. Good call on the datasets as well, I'll host them here and add them to the data folder you guys created last time. Looks like these new projects are getting merged into staging soon, so we're almost there!

Also, I know we briefly touched on cross-browser compatibility for some of these, obviously the test suite itself doesn't work in anything other than chrome yet, but we are going to look at that. Any idea if any of these D3 tests will not work in other browsers?

**Comment by paycoguy** [comment]
We haven't tested the code on other browsers, so we don't really know.
Which browsers and versions are you aiming for?

**Comment by no-stack-dub-sack** [comment]
@paycoguy Good question - I guess general compatibility across latest versions of Safari, Firefox, Chrome, and IE (ugghhh). I don't have FF so I'm bit sure, but I thought at some point we had part of this running in FF and either you or @Christian-Paul mentioned that there were some difficulty with certain tests there...

**Pull request merged**
