### PR TITLE
test shadow DOM behavior

### LINKED ISSUE #269: Buttons move with the button css selector
#### Issue Description

In codepen if you do something like:

button {
margin-left: 100px;
}

it will move the buttons over 100px in the test suite buttons.

#### Browser Information

* Browser Name, Version: Chromium 63
* Operating System: Linux Mint 18.3
* Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen

```
I adjusted for this by just using an id selector but figured it was worth mentioning. 
 
 
```

#### Screenshot

test1

### PR DESCRIPTION
**Pull request by tbushman**
#### Pre-Submission Checklist

- [x] Your pull request targets the `master` branch of freeCodeCamp/testable-projects-fcc
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] Your changes have been tested either locally or using a newly created CDN based on your fork's testable-projects-fcc/build/bundle.js file
- [x] Working changes have been added to the build by running `npm run build`

#### Type of Change

- [ ] Small bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [ ] Tested changes locally.

- [x] Closes currently open issue: Closes #269

#### Description

Using shadow DOM, we can isolate fCC test suite styles from student project styles. This seems to work well with the test UI, but not with the Mocha reporter modal, so I had to treat them separately. If this is approved, I would propose removing many of the `!important` declarations from test-suite.css.
Doesn't work in Firefox, though :/
Update: also would need to update the Selenium queries

### CODE REVIEW

**Comment by tchaffee** [comment]
@tbushman I think this is a good experiment and I love the approach. I have a some doubts about moving this into production. Most importantly, we would like to soon support other browsers and this is still marked as experimental and is only supported by Chrome. Experimental features have been completely dropped in the past. It might just be too early to go with this approach. What about an iframe solution? Would it be possible to run the UI in an iframe but still trigger the mocha tests in the other frame? Usually security consideration prevent that kind of thing, but it's worth brainstorming around. 

For reference, here is the current status of ShadowDom. Looks like it is supported by Chrome, and you can turn it on in FireFox but Edge does not support it. https://caniuse.com/#feat=shadowdom

**Comment by tbushman** [comment]
@tchaffee Cool. I'll work on an iframe.

**Comment by tchaffee** [comment]
@tbushman I have no idea if an iframe will even work... so you might want to do some quick experiments to test it out.

**Comment by tbushman** [comment]
The iframe works for the test runner window but not the mocha reporter modal... which was the same for shadow DOM here. Still, this will keep most of the styles isolated from student projects. When I submit a PR, I will clean up the css names and be able to remove all of the !important declarations for the test window :D ! The other problem will be, as here, accessing the buttons via Selenium... I'll look into that.

**Pull request closed without merging**
