### PR TITLE
Changed keyCodes to use lowercase

### PR DESCRIPTION
**Pull request by philtrem**
#### Pre-Submission Checklist

- [x] Your pull request targets the `master` branch of freeCodeCamp/testable-projects-fcc
- [ ] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [ ] Your changes have been tested either locally or using a newly created CDN based on your fork's testable-projects-fcc/build/bundle.js file
- [ ] Working changes have been added to the build by running `npm run build`

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [x] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [ ] Tested changes locally.

- [ ] Closes currently open issue: Closes #XXX

#### Description
Bug-fix for Drum machine keypress test.
Changed keyCodes array to use lowercase instead of uppercase, so that the test triggers key presses for lowercase characters. 

n.b: this is my first pull request on freecodecamp (or on any open-source repository)
also: feel free to edit as to make the keypress test case insensitive

### CODE REVIEW

**Comment by ValeraS** [comment]
@philtrem The user story says that your drum machine should recognize capital letters.
> User Story #6: When I press the trigger key associated with each .drum-pad, the audio clip contained in its child audio element should be triggered (e.g. pressing the Q key should trigger the drum pad which contains the string "Q", pressing the W key should trigger the drum pad which contains the string "W", etc.).

**Comment by philtrem** [comment]
> @philtrem The user story says that your drum machine should recognize capital letters.
> 
> > User Story #6: When I press the trigger key associated with each .drum-pad, the audio clip contained in its child audio element should be triggered (e.g. pressing the Q key should trigger the drum pad which contains the string "Q", pressing the W key should trigger the drum pad which contains the string "W", etc.).

Keyboards generally represent the key with the capital letter. For instance, the letter 'q' on the keyboard will be represented by its uppercase counterpart, ie. 'Q'. By default, pressing 'Q' will print the lowercase letter to the screen, it is only when CAPS LOCK is activated that the uppercase letter will be printed instead.

Also, it little sense to expect the user to switch on CAPS LOCK to use the drum machine. You may want to make it case insensitive (ie. make it work regardless of whether CAPS LOCK is on or not), but otherwise if you have to choose one between lowercase and uppercase, it would have to be lowercase. 

To take on your point directly, it doesn't explicitely say that you should have to press CAPS LOCK to use the drum machine, or that you need to make it work only for capital/uppercase letters.

**Comment by abhishekakade** [comment]
I did mine using [key codes](https://css-tricks.com/snippets/javascript/javascript-keycodes/) - [drum machine](https://abhishekakade.github.io/drum-kit/). Works regardless on caps lock status that way.

**Comment by philtrem** [comment]
> I did mine using [key codes](https://css-tricks.com/snippets/javascript/javascript-keycodes/) - [drum machine](https://abhishekakade.github.io/drum-kit/). Works regardless of caps lock status that way.

The test will pass if you check for both the lowercase key and the uppercase key works, but the test is still flawed. Using keycodes for lowercase letters would still 'cause the test to fail. So you'd have to check for both cases, or for uppercase only (which makes little sense).

**Comment by RandellDawson** [comment]
@moT01 I just checked my project and the demo project on Codepen and both work regardless if the caplock is on or off and both pass all the tests.  I don't think this PR is even needed. What do you think?

**Comment by moT01** [comment]
Sounds good to me @RandellDawson.

    Thank you for opening this pull request.

    This is a standard message notifying you that we've reviewed your pull request and have decided not to merge it. We would welcome future pull requests from you.

    Thank you and happy coding.

**Comment by philtrem** [comment]
> I did mine using [key codes](https://css-tricks.com/snippets/javascript/javascript-keycodes/) - [drum machine](https://abhishekakade.github.io/drum-kit/). Works regardless of caps lock status that way.

Yeh, but that's the issue. It doesn't work if you use the string values instead of keycodes. Meaning that valid solutions get discarded.

**Pull request closed without merging**
