### PR TITLE
feat: change to target=top on quote machine tweet btn

### PR DESCRIPTION
**Pull request by moT01**
#### Pre-Submission Checklist

- [x] Your pull request targets the `master` branch of freeCodeCamp/testable-projects-fcc
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] Your changes have been tested either locally or using a newly created CDN based on your fork's testable-projects-fcc/build/bundle.js file

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.

- [ ] Closes currently open issue: Closes #XXX

Related to:
https://github.com/freeCodeCamp/freeCodeCamp/issues/40089
https://github.com/freeCodeCamp/freeCodeCamp/pull/40118

### CODE REVIEW

**Review by nhcarrigan — APPROVED** [review]
LGTM~! 🥳 

Pulled this change into a [CodePen](https://codepen.io/nhcarrigan/pen/mdEGWYz) and tested on Chrome - tweet button worked with this change.

**Review by RandellDawson — APPROVED** [review]
LGTM

**Comment by RandellDawson** [comment]
Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 🎉

@moT01 Go ahead and update the freeCodeCamp pen.

**Comment by moT01** [comment]
Thanks for the quick reviews @nhcarrigan & @RandellDawson 🎉 I updated the project on codepen.

**Pull request merged**
