### PR TITLE
fix: update paths to build.js CDNs

### PR DESCRIPTION
**Pull request by SubhrajyotiSen**
#### Pre-Submission Checklist

- [x] Your pull request targets the `master` branch of freeCodeCamp/testable-projects-fcc
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] Your changes have been tested either locally or using a newly created CDN based on your fork's testable-projects-fcc/build/bundle.js file
- [ ] Working changes have been added to the build by running `npm run build`

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.

- [ ] Closes currently open issue: Closes #XXX

#### Description

This commit updates the links to the CDNs to the recently relocated paths.

### CODE REVIEW

**Comment by tchaffee** [comment]
@SubhrajyotiSen This looks good. Could you point me to where the paths have been changed? I'm guessing there is a PR in another repo? Thanks.

**Comment by tbushman** [comment]
@SubhrajyotiSen Thanks. I want to clear something up on the CDN. Please also see #485  

Are we not moving to `https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js` as referenced in the Codepen templates (or is it now `https://cdn.freecodecamp.org/testable-projects-fcc/master/build/testable-projects-fcc/v1/bundle.js` ?)   

Is `https://gitcdn.link/repo/freeCodeCamp/testable-projects-fcc/master/build/testable-projects-fcc/v1/bundle.js` for something else?

**Comment by tchaffee** [comment]
@raisedadead Maybe you can help us understand this?

**Comment by tbushman** [comment]
@SubhrajyotiSen (I've) been pointing students to a different link :/  
`https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js`

See https://github.com/freeCodeCamp/cdn  
  
I'll wait to hear from @raisedadead on this if that's ok. Thanks for your work.

**Comment by raisedadead** [comment]
Yes you are right @tbushman. The correct path is `https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js`

**Comment by SubhrajyotiSen** [comment]
In that case, what should the 2 correct URLs be since the current ones do not work?

**Comment by tchaffee** [comment]
@SubhrajyotiSen For production, the correct URL is https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js

For dev, it definitely should not be https://rawgit.com/freeCodeCamp/testable-projects-fcc/master/build/testable-projects-fcc/v1/bundle.js due to the way rawgit permanently caches. Rawgit should always reference a specific commit. For now, you could use the latest commit, but I'm a bit concerned that we need to constantly update the docs with that approach. @tbushman @raisedadead any thoughts on this?

**Comment by tbushman** [comment]
@tchaffee I've been telling everyone `https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js` as @raisedadead confirmed and now I'm wondering if the plan is for the `/v1/` portion to increment and then there's another problem. I'll be getting into #402 at some point when I'm sure this will become more apparent.

**Comment by raisedadead** [comment]
The `v1` part is just there in case we do a `major breaking change` on the bundle. So when we would have a major change like `v2` the older bundle can co-exist to support projects that are built on it.

Now coming to the URLs themselves. We can upload a dev version of the same at a path `v1/dev/` ? This can be done in the #402 work??

**Comment by tchaffee** [comment]
@raisedadead The versioning approach makes a lot of sense. It allows us to make changes to project requirements and other breaking changes while older projects still pass the older tests.

Concerning the dev version,  is it even needed anymore? In the past we needed it because we didn't have control of the caching policy of the CDN. Almost all of our dev testing is done with a locally created `bundle.js` anyway. It's very rare we need to do dev tests using an actual CDN. I think we can safely take the dev CDN out of the docs and if we need something like that in the future we can create it as needed. Now that we have control using our own CDN it makes everything more flexible and future proof.

**Comment by raisedadead** [comment]
> Almost all of our dev testing is done with a locally ...

I was under the impression that user's are using for developing projects on CodePen in a dev mode. But if that's not the case we should totally remove the references, and also text around CDN caching, which is irrelevant now.

**Comment by SubhrajyotiSen** [comment]
@raisedadead Can I update the section to read as

### Bundle CDN:
https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js
  - can take 2hrs or more to propagate changes to all users

**Comment by raisedadead** [comment]
@SubhrajyotiSen the changes will be updated instantly on our CDN. So that is irrelevant as well. I think we can drop the entire section other than the URL itself.

I am waiting a confirmation from @tchaffee that the dev version will not be used by end users. If not we are good to go.

**Comment by raisedadead** [comment]
Once we have the confirmation, this:

>
> ### Bundle CDNs:
> - FOR PRODUCTION: https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js
>     - will not throttle our traffic
>     - can take 2hrs or more to propagate changes to all users
> - FOR DEV: https://rawgit.com/freeCodeCamp/testable-projects-fcc/master/build/bundle.js
>     - will throttle heavy traffic
>     - changes will propagate much quicker so replace the gitCDN link with this for testing


should be updated to this:

> ### Bundle CDNs:
> [`https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js`](https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js)

**Comment by SubhrajyotiSen** [comment]
Thanks. I will update it post the confirmation

**Comment by SubhrajyotiSen** [comment]
I have updated the PR accordingly

**Comment by raisedadead** [comment]
Thanks @SubhrajyotiSen !

**Comment by raisedadead** [comment]
Hey @SubhrajyotiSen I just noticed that this can be updated on the readme as well.

**Comment by SubhrajyotiSen** [comment]
@raisedadead I will do it

**Pull request merged**
