### PR TITLE
Deleted the main tests for alignment D3

### PR DESCRIPTION
**Pull request by tchaffee**
#### Pre-Submission Checklist

- [x] Your pull request targets the `master` branch of freeCodeCamp/testable-projects-fcc
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] Your changes have been tested either locally or using a newly created CDN based on your fork's testable-projects-fcc/build/bundle.js file
- [ ] Working changes have been added to the build by running `npm run build`

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.

- [ ] Closes currently open issue: Closes #XXX

#### Description
Removed the main tests for alignment D3 because they are redundant. They basically just try to recreate the DOM that already exists in the official CodePens for the D3 projects.

### CODE REVIEW

**Comment by tchaffee** [comment]
@tbushman I've thought long and hard about this and I keep coming to the same conclusion: the D3 tests do not make sense. It's mostly just repeating a DOM that is already out there on the CodePens. 

These D3 tests run against the CodePens already. No need to recreate a simpler version of the CodePen DOMs and do that again locally. The main point of the tests is to make sure that something doesn't get broken. And we can already detect if someone breaks alignment-D3.js with the existing CodePen tests. 

The other goal of tests is to document how stuff is intended to be used or how it works. I don't think the D3 tests achieved that. They were hard to understand and did not document how to use the  alignment-D3.js. Just as easy to look at the D3 CodePen tests to see how that file is supposed to be used.

I have kept the other small tests alignment-D3-support.js because those are much more focused and do help document what that code is supposed to be doing.

**Comment by tchaffee** [comment]
Anyone understand the Travis error? I can't figure it out. @tbushman @ValeraS 

BTW, Travis builds are taking up to 12 hours. Probably because of Hacktoberfest.

**Comment by ValeraS** [comment]
> Deleted the tests for alignment D3
> ✖   message may not be empty [subject-empty]
> ✖   type may not be empty [type-empty]
> ✖   found 2 problems, 0 warnings

fix commit's comment.

**Comment by ValeraS** [comment]
On your local repo run `yarn install` and amend your commit. You should see this message.

Your commit message should be in the format `type(scope): message`.

**Comment by tchaffee** [comment]
Strangely `yarn install` showed `success Already up-to-date`. Not sure how I got away with the invalid commit message the first time, but no big deal. It's working now.

**Comment by tchaffee** [comment]
Hopefully this build won't take 12 hours for me to see the results like last time! :-D

**Comment by tbushman** [comment]
@tchaffee I agree very much about the tests of the alignment tests. They were great for the TDD phase.

**Comment by tchaffee** [comment]
@tbushman After 8+ hours of waiting for Travis and then Github itself crashing, this is finally ready to merge! :-D

**Comment by tbushman** [comment]
LGTM!

**Pull request merged**
