### PR TITLE
fix(test): Allow button element for form submit

### PR DESCRIPTION
**Pull request by lasjorg**
#### Pre-Submission Checklist

- [x] Your pull request targets the `master` branch of freeCodeCamp/testable-projects-fcc
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] Your changes have been tested either locally or using a newly created CDN based on your fork's testable-projects-fcc/build/bundle.js file

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.

- [ ] Closes currently open issue: Closes #XXX

#### Description

Just a quick PR to allow the submit button to be a button element. There is really no good reason why it should be limited to just an input element.

### CODE REVIEW

**Review by ShaunSHamilton — APPROVED** [review]
I am happy with this. Thanks, Lasse

LGTM 👍 

---

In general, we try as much as possible not to change user-stories for certification projects. However, I wonder if we can make an exception for this, because the change would not invalidate previous projects. @scissorsneedfoodtoo ?

**Comment by lasjorg** [comment]
This shouldn't affect anything except allow new projects to use a button as well as an input. However, we should update `User Story #11` to reflect this change if/when merged.

**Comment by ShaunSHamilton** [comment]
> However, we should update User Story #11 to reflect this change if/when merged.

_Should_ we, though? At the end of the day, I am happy allowing a `button` to pass the tests. However, we try very hard to not change user-stories - even if the user story seems like an unnecessary requirement

Example:
> Make the `div` `blue`.

If a Camper makes it `red`, they clearly know how to set background colours, but the specification asked for `blue`.

---

Again, personally, I am fine with the change, but emphasize the disdain towards changing certification user-stories.

**Comment by lasjorg** [comment]
I wouldn't call it an unnecessary requirement, but an odd requirement. I'd also like to point out that [we teach it](https://www.freecodecamp.org/learn/responsive-web-design/basic-html-and-html5/add-a-submit-button-to-a-form) using a button element and that what I'm proposing is what we already do now for the survey form project, i.e. allow for both elements and call it a button in the user story ([test](https://github.com/freeCodeCamp/testable-projects-fcc/blob/main/src/project-tests/survey-form-tests.js#L362)). So it really isn't unreasonable to do the same for the product page form requirement. 

---

It's not a breaking change as it is inclusive of the current requirement. Allowing for a button element just adds another way of completing the requirement without removing or changing anything about the current requirement. Personally, I don't see the issue with allowing both an input and a button and having the user story simply call it a submit button.

**Review by naomi-lgbt — APPROVED** [review]
I'm happy to discuss further whether we update the user story, but I think we should go ahead and land this.

**Pull request merged**
