### PR TITLE
fix(config): Remove "prettier/react" from the extends array

### PR DESCRIPTION
**Pull request by lasjorg**
#### Pre-Submission Checklist

- [x] Your pull request targets the `master` branch of freeCodeCamp/testable-projects-fcc
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] Your changes have been tested either locally or using a newly created CDN based on your fork's testable-projects-fcc/build/bundle.js file

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.

- [ ] Closes currently open issue: Closes #XXX

#### Description

I get an error when running `yarn lint`. This PR removes "prettier/react" from the extends array.

eslint-config-prettier version 8 has merged the configs
https://github.com/prettier/eslint-config-prettier/blob/main/CHANGELOG.md#version-800-2021-02-21

---

Just as an aside. I have always gotten tons of formatting error related end of line formatting (LF/CR RCLF) with this repo. I usually just add `"prettier/prettier": ["error", { "endOfLine": "auto" }]` to the config. Do we want to allow for mixed end of lines?

### CODE REVIEW

**Comment by scissorsneedfoodtoo** [comment]
Awesome, thanks for taking care of this @lasjorg.

About the end of line option, sure, either `auto` or the default `lf` sounds like it would be really helpful here.

Would you like to handle it in this PR, or open up a new one?

**Comment by lasjorg** [comment]
@scissorsneedfoodtoo Sorry for the late reply.

I don't actually know what the correct setup should be. Maybe we can use the same setup as the main repo. I have never had any issue with that.

Maybe we can get a little help or guidance from someone that has set up the main repo tooling. As far as I can tell the main repo enforces LF line endings but I never had the same issues as I do with this repo. I know it uses .gitattributes and different configs as well as what looks to be a different setup of husky and lint-staged. Not sure if there is an issue with how the pre-commit hooks are set up in this repo.

**Comment by scissorsneedfoodtoo** [comment]
Hi @lasjorg, no worries. Thanks for your patience and for bringing this up.

I'm not that familiar with the current tooling in the main repo, but I do see that its `.prettierrc` file has more settings than the one in this repo, including one for LF line endings: "endOfLine": "lf"`

I think a good addition to this or another PR would be to copy over all the `.prettierrc` settings from the main repo over to the `.prettierrc` file here.

With the Prettier extension installed, that should take care of LF issues as contributors edit individual files.

Also, the current plan is to clean up some of the old Mocha files that we no longer need now that Cypress is in place, and to set up the `test` scripts in `package.json` so that we can use the `pretest` script to handle linting and formatting. With that in place, we should be able to catch any other cases where files don't end with a line feed.

**Comment by scissorsneedfoodtoo** [comment]
Hi @lasjorg, thanks for your patience and for this fix. I'll go ahead and merge it now.

Also, thanks for bringing up possible improvements to the Prettier config here. We can look at improving that in another PR.

**Review by scissorsneedfoodtoo — APPROVED** [review]

**Pull request merged**
