### PR TITLE
fix: alter 25+5 timer to work with react@18

### PR DESCRIPTION
**Pull request by anlach**
#### Pre-Submission Checklist

- [x] Your pull request targets the `master` branch of freeCodeCamp/testable-projects-fcc
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] Your changes have been tested either locally or using a newly created CDN based on your fork's testable-projects-fcc/build/bundle.js file

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.

- Related to https://github.com/freeCodeCamp/freeCodeCamp/issues/45922

#### Description

I am making a new PR to use a proper "fix/" branch name...

Concurrency added to React 18 broke tests because it meant state could not be tested immediately after calling setState. This update to the 25 + 5 Clock tests adds some extra delays where it was needed to wait for React to update state.

The tests also revealed an error in the code example, which would allow the timer to read "0-1:59" when the timer was -1. The error message here was improved, and the example was fixed.

### CODE REVIEW

**Comment by lasjorg** [comment]
With this PR the example project is passing with both React 17 and 18. 

@anlach Did you test this with your own project? If you run the build the test script is inside `build\testable-projects-fcc\v1`

My old project is still failing with React 18 (but who knows, it might be a bug it's an old project). I'm not sure, but it might be because the example project isn't using function components and hooks. If anyone else has a version of this project that uses hooks and can test with the PR and React 18 that would be great.

If nothing else, the PR at least does make the example project work with React 18.

**Comment by anlach** [comment]
> With this PR the example project is passing with both React 17 and 18.
> 
> @anlach Did you test this with your own project? If you run the build the test script is inside `build\testable-projects-fcc\v1`
> 
> Edit: it looks like your own project is also using classes so I'm guessing it works as well.
> 

@lasjorg I didn't update my project to test it with React 18, but that shouldn't be too hard, so I'll let you know.

**Comment by lasjorg** [comment]
@anlach I think it likely will as your code is using classes, setState, and lifecycle methods. I think the main issue is with hooks and function components where the test delays doesn't always seem to fix it the same way as it does with older code.

**Comment by anlach** [comment]
@lasjorg I guess I'm struggling a bit to run the tests on my project. I don't have access to the new tests in the codepen, so I can't run them there, so I attempted to replace the source code in my clone of the repo. However, when I try to run the test, none of the tests seem to load. It says "passing 0/0".  Is there something obvious that I'm missing. I don't see any error messages, but there must be some hidden somewhere...

**Comment by anlach** [comment]
Oh, I guess I have to add the tests in manually to the project, since you guys must do that behind the scenes somehow in CodePen.

**Comment by anlach** [comment]
@lasjorg Okay, I got it figured out - had to set the projectName variable. You were right, and they all passed.

**Review by lasjorg — APPROVED** [review]
Even though this PR will likely not fix the issue for everyone, as said, it still fails with my own project using functions/hooks.

At least it makes the example project pass using React 18, so I'm good with it.

**Review by naomi-lgbt — APPROVED** [review]
__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

**Pull request merged**
