### PR TITLE
fix(project): Remove scss, update selectors

### PR DESCRIPTION
**Pull request by lasjorg**
#### Pre-Submission Checklist

- [x] Your pull request targets the `master` branch of freeCodeCamp/testable-projects-fcc
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] Your changes have been tested either locally or using a newly created CDN based on your fork's testable-projects-fcc/build/bundle.js file
- [x] Working changes have been added to the build by running `npm run build`

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.

- [x] Closes currently open issue: Closes https://github.com/freeCodeCamp/testable-projects-fcc/issues/804

#### Description

1. Remove the use of SCSS.

2. Added one new class `.product`. The products now have more reasonable selectors.

3. Change descendant selectors to child selectors where possible.

**Note:** This is still missing the font awesome icons as I don't know how to link to them in a file with no HTML/Body elements.

### CODE REVIEW

**Comment by tbushman** [comment]
@lasjorg It looks like you can include the script itself as a `.js` or `.jsx` file in the same directory or inside a `./scripts` or `./js` or `/anyname` directory:  
  
`gulpfile.js`  

```  
function js(projectPath) {
  return pipeline(
    gulp.src(projectPath + '/**/*.{js,jsx}'),
    babel(babelOptions).on('error', err => {
      const message = err.toString();
      process.stderr.write(`${message}\n`);
      this.emit('end');
    }),
    concat('index.js'),
    noop
  );
}   
```

**Comment by tbushman** [comment]
...here's an example of including a `<script>` tag (src/projects/random-quote-machine/index.html):  
```  
</div> <---closing "</div>"
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.0/jquery-ui.min.js"></script>
```

**Comment by tbushman** [comment]
@lasjorg Everything else looks spot-on. Thanks.

**Comment by lasjorg** [comment]
@tbushman You are right, thanks.

I should really have been able to figure that out myself by looking at the other projects, sorry. I just thought it would be more complicated for some reason.

**Comment by tbushman** [comment]
@lasjorg LGTM! Thanks for your contributions and patience.

**Pull request merged**
