### PR TITLE
fix: load marked for the markdown-previewer test

### LINKED ISSUE #430: Markdown previewer #Tests 3 failing when using onChange event in local react environment using create-react-app
#### Issue Description

When I use the onChange event to update the textarea values in both the #editor element and the #preview element in markdown previewer project in a local react environment using the create-react-app,  the #Tests 3 is failing even though I am able to satisfy the user story which is to update the #preview element as I type in the #editor element.

#### Browser Information

* Browser Name, Version: Google Chrome, 67.0.3396.99 (Official Build) (64-bit)
* Operating System: Ubuntu 18.04 LTS (64-bit)
* Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen

```
`import React, { Component } from 'react';

class App extends Component {
  constructor(props) {
    super(props);
    this.state = {
      value: '',
    }
    this.handleChange = this.handleChange.bind(this);
  }

  handleChange(e) {
    this.setState({
      value: e.target.value
    });
  }

  render() {
    return (
     <div>
       <textarea id="editor" value={this.state.value} onChange={this.handleChange}></textarea>
       <textarea id="preview" value={this.state.value}></textarea>
     </div>
    );
  }
}

export default App;` 
 
 
```

#### Screenshot

screenshot from 2018-07-09 18-38-39

### LINKED ISSUE #531: Markdown Previewer and marked.js
I use marked.js as a dependency in `package.json`

```js
{
  "name": "markdown-previewer",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "marked": "^0.4.0",
    "react": "^16.4.2",
    "react-dom": "^16.4.2",
    "react-scripts": "1.1.4"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject"
  }
}
```

and import it into my component

```jsx
import React from "react";
import marked from "marked";

const Preview = props => {
  const result = { __html: marked(props.value) };

  return <div id="preview" dangerouslySetInnerHTML={result} />;
};

export default Preview;
```

The app works but in order to pass tests 3-6 I need to additionally include `marked` file as a `script` tag

### PR DESCRIPTION
**Pull request by ValeraS**
#### Pre-Submission Checklist

- [x] Your pull request targets the `master` branch of freeCodeCamp/testable-projects-fcc
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] Your changes have been tested either locally or using a newly created CDN based on your fork's testable-projects-fcc/build/bundle.js file
- [ ] Working changes have been added to the build by running `npm run build`

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.

- [x] Closes currently open issue: Closes #531 closes #430

### CODE REVIEW

**Comment by tbushman** [comment]
Possibly closes #430 .

**Comment by tbushman** [comment]
@ValeraS This needs a rebase and then I'll merge it.  
Also, I'm wondering if I was premature merging the mocha reporter PR (#591) -- does that negate #556 ?

**Comment by ValeraS** [comment]
@tbushman, have rebased this and #556.

**Comment by tbushman** [comment]
LGTM!

**Pull request merged**
