### PR TITLE
Updated the tests to reflect changes in PR #34756

### PR DESCRIPTION
**Pull request by kevindelsh**
As proposed in PR https://github.com/freeCodeCamp/freeCodeCamp/pull/34756 , the tribute page needs to have a `<figure>` and `<figcaption>` element with corresponding ids to pass.
Tests have been updated to reflect those instructions.

#### Pre-Submission Checklist

- [x] Your pull request targets the `master` branch of freeCodeCamp/testable-projects-fcc
- [ ] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] Your changes have been tested either locally or using a newly created CDN based on your fork's testable-projects-fcc/build/bundle.js file
- [x] Working changes have been added to the build by running `npm run build`

#### Type of Change

- [ ] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [x] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.

- [ ] Closes currently open issue: Closes #XXX

### CODE REVIEW

**Comment by thecodingaviator** [comment]
@kevindelsh You had a problem wherein the linting of the commit was failing, I've fixed it

**Comment by thecodingaviator** [comment]
As per the established procedure, @QuincyLarson / @no-stack-dub-sack please provide reviews on this. This is a breaking change and since we've released the curriculum, this is something that we should take into consideration. These changes would break all existing projects

**Comment by kevindelsh** [comment]
Thanks, @thecodingaviator for your support and correction.

@QuincyLarson & @no-stack-dub-sack, here are two ideas that may not be practical or be even naive (but who knows?):

We could check for both scenarios:
1. Where both implementations (with old elements `<div>` and new semantically correct ones `<figure>`, `<figcaption>`) are checked for and accepted. The current state of the tests partially provides for that.
2. Where both implementations are checked for and accepted but for older implementations a **hint/warning** is shown that advises students to implement the best practice.

This **won't be breaking** because older projects will still pass (with or without a hint or warning).

Since our instructions are updated and ask for `<figure>` and `<figcaption>` students, for the most part, will learn, write, and test for `<figure>` and `<figcaption>`.

Hope that makes sense.

**Comment by QuincyLarson** [comment]
@tchaffee What do you think of @kevindelsh's suggestion here?

**Comment by tchaffee** [comment]
I'm not entirely convinced (yet) that `<figure>` is actually the correct element to use for a tribute page which is supposed to _feature_ a photo of the person. Per the [w3c specification](https://w3c.github.io/html-reference/figure.html), "The figure element represents a unit of content, optionally with a caption, that is self-contained, that is typically referenced as a single unit from the main flow of the document, **and that can be moved away from the main flow of the document without affecting the document’s meaning**." Emphasis mine. The photo in the case of our Tribute Page is an essential feature of the content, no? I've read in other articles that a banner for a page should *not* use `<figure>` because it should not be moved away from the main flow. Isn't our photo a sort of page banner?
I suppose it could be argued that the photo could be moved to the end of the document without affecting the meaning?
Are we teaching all of the nuances above in the lessons that come before the Tribute Page project?
I see only one lesson that talks about the `<figure>` element, and it talks about accessibility. So the lessons as-is are confusing unless we consistently always use the new tag when appropriate and explain when and when not to use the new tag. For sure no potential employer is going to throw out a candidate who uses ``, which is used everywhere.
Either way, I'm not opposed to this change and encourage students to learn newer tags. I would be happy to merge it if @QuincyLarson approves it. In which case the tests should be changed per @kevindelsh  suggestion to allow "both implementations (with old elements <div> and new semantically correct ones <figure>, <figcaption>) are checked for and accepted."

**Comment by QuincyLarson** [comment]
@tchaffee Thanks for your candid and well-reasoned thoughts on this.

@kevindelsh We could (and most likely, will) teach the `<figure>` element and some of the other new HTML5 elements as part of the upcoming freeCodeCamp curriculum overhaul. (more on that here in case you haven't seen this yet: https://www.freecodecamp.org/forum/t/help-us-build-version-7-0-of-the-freecodecamp-curriculum/263546) This is the first project, and we want to be careful not to  intimidate people with unfamiliar tags, so I think we should wait until the curriculum is updated before we attempt to update the instruction text itself - though we could update the tests to pass when people independently choose to use these new elements instead of the old elements.

@thecodingaviator it's been a few weeks since this was last updated and the build failed - could you QA this real quick?

**Comment by thecodingaviator** [comment]
@QuincyLarson I just went over the build real quick, it is failing since the sample CodePen project is built according to the old tests the new tests break the project. We have three ways to go ahead from here:

1. We leave this as is and close the PR while making sure this gets integrated into the new curriculum.

2. We change the tests to accept both cases and the text to reflect only the new specifications, this way, old projects would not break and new projects could use the new specs but would lead to edge cases wherein someone might use a tutorial or something to do the project the old way i.e. with <div>, but the tests would say <figure> which might confuse the user.

3. We change the tests to accept both as well as make the text day that the user can use both, but since <figure> is a new element, I’m not sure how many users would be comfortable using it

**Comment by thecodingaviator** [comment]
As far as further QAing goes, I’ll have a look at all changes shortly, re run the build once and get back

**Comment by thecodingaviator** [comment]
@QuincyLarson I re-ran the build and everything looks fine to me except the fact stated above that this is obviously a breaking change and the CodePen project would need to be updated accordingly

**Comment by scissorsneedfoodtoo** [comment]
Hey @kevindelsh,

Thank you for opening this pull request.

This is a standard message notifying you that we've reviewed your pull request and have decided not to merge it. We would welcome future pull requests from you.

As mentioned in [this issue](https://github.com/freeCodeCamp/freeCodeCamp/pull/34756), we'll need to further evaluate how to introduce the `figure` element in the current curriculum. We'll also need to adjust the tests to accept either a `div` or `figure` element before going forward with this change.

Thanks again and happy coding.

**Pull request closed without merging**
