### PR TITLE
fix: trigger input event on a react element

### PR DESCRIPTION
**Pull request by ValeraS**
#### Pre-Submission Checklist

- [x] Your pull request targets the `master` branch of freeCodeCamp/testable-projects-fcc
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] Your changes have been tested either locally or using a newly created CDN based on your fork's testable-projects-fcc/build/bundle.js file
- [ ] Working changes have been added to the build by running `npm run build`

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.

- [ ] Closes currently open issue: Closes #XXX

### CODE REVIEW

**Comment by tbushman** [comment]
@ValeraS One of the cases where we had to configure the audio element, and we got it working with our previous ObjectProperties config. was: https://codepen.io/vipatron/pen/wjzYJo .
Can you test that and see why it's not passing currently and also with this PR?  
We might want to consider using the whole react-trigger-change library to catch all input types. But we need to ensure we're including the audio element additionally.

**Comment by ValeraS** [comment]
@tbushman I have checked it in this Codepen early, and it works correctly. In the Codepen you'll need to change a switch condition in function `handleKeyDown` to `event.key.toLowerCase()`. The previous solution has worked because the assertion always was true if you had an audio element.

Not sure about the library, by for now it needed only in the markdown-previewer test and only for an input event.

**Comment by tbushman** [comment]
@ValeraS You're right. It's a separate issue. To be clear though, the test that isn't passing is # 6 :   
```
assert.isFalse(
    el.paused,
    'No audio plays when the ' + el.id + ' key is pressed '
);  
```   
, ever since the ObjectProperties configuration was removed. This PR addresses the problem with react-triggering for `<textarea>`, so I'll merge this, but I'm curious what's going on with the audio element in drum-machine since a similar configuration was removed in #576. 
We can consider having a general utility for enabling event triggering on more element types.

**Comment by ValeraS** [comment]
@tbushman I'll try to explain. For a `value` attribute of `input` and `textarea` elements, the React library defines own setter, which caches a set value. When an input event triggered it checks a current value with the cached value and if they equal does nothing. For the attributes of an `audio` element, React doesn't change anything. Also, for an audio element, we don't trigger any events and only check attributes values in our tests.

**Comment by tbushman** [comment]
@ValeraS At some point maybe you'll explain why that test now fails since you removed the ObjectProperties configuration in #576. Your previous explanation wasn't applicable.

**Comment by ValeraS** [comment]
@tbushman Sorry, I don't understand what do you mean by `why that test now fails`? In the https://codepen.io/vipatron/pen/wjzYJo test # 6 fails because the function `handleKeyDown` in this pen only handle lowercase key but we send uppercase key and because of this audio doesn't play and assert fails.

**Comment by tbushman** [comment]
@ValeraS I meant that it wasn't failing before.

**Comment by ValeraS** [comment]
@tbushman 
> The previous solution has worked because the assertion always was true if you had an audio element.

You have had `assert.isNotOk(audio.paused)`, which always was true because `paused` was undefined.

**Pull request merged**
