### PR TITLE
fix: wrote more precise regular expressions for tests

### LINKED ISSUE #489: [Front End Libraries Projects - Markdown Previewer] - Tests don't pass, markdown works visually!
#### Issue Description

The pen visually meets all the non-optional user stories mentioned in the [project requirements page](https://learn.freecodecamp.org/front-end-libraries/front-end-libraries-projects/build-a-markdown-previewer)

However, the tests suite doesn't recognise the default input text and the default markdown preview that is initialised when the page loads. 

Tried a fully jQuery approach using a variable to store the text and writing that to the `<textarea>`. Also tried an HTML approach (which is what the pen currently has).

#### Browser Information

* Browser Name, Version: Chrome 67.0.3396.99
* Operating System: macOS
* Mobile, Desktop, or Tablet: laptop

#### Your Code / Link to Your Pen

[See pen here]( https://codepen.io/numoonchld/pen/EpwYNO)

#### Screenshot

screenshot_2018-07-27 fcc markdown previewer

### PR DESCRIPTION
**Pull request by ValeraS**
#### Pre-Submission Checklist

- [x] Your pull request targets the `master` branch of freeCodeCamp/testable-projects-fcc
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] Your changes have been tested either locally or using a newly created CDN based on your fork's testable-projects-fcc/build/bundle.js file
- [x] Working changes have been added to the build by running `npm run build`

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.

- [x] Closes currently open issue: Closes #489 

#### Description

- supported two styles of headers, Setext and atx
- supported creating codeblock with at least 4 spaces or 1 tab indenting
- more precise regular expressions

### CODE REVIEW

**Comment by tbushman** [comment]
@ValeraS Thank you very much for all your help. I'm using regex101.com to check these.  
Is `(?<!(?:[ ]{4}|\t)[ \t]*)` supposed to be `(?:<!(?:[ ]{4}|\t)[ \t]*)` (non-capturing group)?  
I'm going to run it locally and test a few projects to make sure. It looks like you know your regex so I'm just making sure.

**Comment by ValeraS** [comment]
@tbushman No, it isn't. (?< ... ) is negative lookbehind.
regex101 says the feature is not yet supported on all browsers, but chrome supports it.

**Comment by tbushman** [comment]
@ValeraS These all check out. Really exceptional work! So glad to have your expertise. LGTM! We need to update documentation on some of these. Do you want to do that? It would involve a short synopsis of some of the more complex regexeps you've written. If not I'll merge this anyways. Awesome work.

**Comment by ValeraS** [comment]
@tbushman Added a comment for (?<! ...) and replaced notStrictEqual with isTrue.
The commit was amended.

**Comment by tbushman** [comment]
@ValeraS Awesome. Thank youuuuu!

**Comment by tbushman** [comment]
@ValeraS The regexps break the tests in firefox, which I know we're not supposed to care about. But I was reading somewhere that we can wrap regexps like `new RegExp(//)` and that might help the tests fail more gracefully in ff rather than breaking. What do you think? I want to clear that up before I merge this into the CDN...

**Pull request merged**
