### PR TITLE
test: testing travis env

### PR DESCRIPTION
**Pull request by lasjorg**
Just a test

### CODE REVIEW

**Comment by tbushman** [comment]
@lasjorg Great find. Do you mind if I just merge this? I think these package updates will help other PRs.

**Comment by lasjorg** [comment]
@tbushman Wouldn't it be better to update https://github.com/freeCodeCamp/testable-projects-fcc/pull/1149 with the changes to the `.travis.yml` from this PR?

**Comment by tbushman** [comment]
@lasjorg That would be fine. I'll merge a PR if you open it.

**Comment by lasjorg** [comment]
@tbushman I think it's fine like it is now.

Having the .travis.yml changes in your PR that makes dependency updates seems fitting anyway.

**Comment by lasjorg** [comment]
Testing done, closing.

**Pull request closed without merging**
