### PR TITLE
fix(project): update audio file link to use fCC CDN

### LINKED ISSUE #1146: Update audio file link for Pomodoro Clock example project
@scissorsneedfoodtoo @tbushman

The current link used for the [Pomodoro Clock example project](https://codepen.io/freeCodeCamp/pen/XpKrrW) on Codepen does not work.

```
GET https://www.peter-weinberg.com/files/1014/8073/6015/BeepSound.wav net::ERR_CERT_COMMON_NAME_INVALID

pen.js:166 Uncaught (in promise) DOMException: The element has no supported sources.
```

I made a PR on the CDN repo, after it has been approved we can update the link on Codpen.
https://github.com/freeCodeCamp/cdn/pull/50

### PR DESCRIPTION
**Pull request by lasjorg**
#### Pre-Submission Checklist

- [x] Your pull request targets the `master` branch of freeCodeCamp/testable-projects-fcc
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] Your changes have been tested either locally or using a newly created CDN based on your fork's testable-projects-fcc/build/bundle.js file

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
  
- [x] Closes currently open issue: Closes #1146

#### Description

This PR updates the link to the audio file to use the fCC CDN.

Note: the diff is a little noisy because of the Prettier formatting (single to double quotes).

### CODE REVIEW

**Comment by lasjorg** [comment]
@tbushman Not sure why it is failing the CI, the yarn/npm build works fine locally.

**Comment by lasjorg** [comment]
Node/Babel issue perhaps?
https://github.com/nodejs/node/issues/32852#issuecomment-613655150
https://github.com/babel/babel/issues/11427#issuecomment-614584591

The build works locally, both with Node v12.16.1 and v12.18.0, I'm not sure why CI is failing. 

Local Node: v12.16.1 works
Local Node: v12.18.0 works

CI Node: v12.18.0 fails

`Cannot find module '@babel/compat-data/corejs3-shipped-proposals'`

**Comment by lasjorg** [comment]
Synced up with master to get the changes from https://github.com/freeCodeCamp/testable-projects-fcc/pull/1149, CI is now passing again. I did a `--amend` hope that's OK.

**Comment by tbushman** [comment]
@lasjorg Fantastic. :D LGTM!

**Pull request merged**
