### PR TITLE
use getBoundingClientRect for determining img centering

### LINKED ISSUE #111: Determining if img tag is centered in Tribute Page
#### Issue Description

Computed margin in Firefox returning "" in test 2 (The  element should be centered within its parent element.). Suggestion: if margin = "", check margins with getBoundingClientRect(). PR forthcoming.

#### Browser Information

* Browser Name, Version: Firefox
* Operating System: macOS Sierra 10.12.1
* Mobile, Desktop, or Tablet: Desktop

### PR DESCRIPTION
**Pull request by tbushman**
#### Pre-Submission Checklist

- [x] Your pull request targets the `master` branch of freeCodeCamp/testable-projects-fcc
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] Your changes have been tested either locally or using a newly created CDN based on your fork's testable-projects-fcc/build/bundle.js file
- [x] Working changes have been added to the build by running `npm run build`

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue: Closes #111, #121

#### Description

This simplifies the test for checking centering of img element within parent element. Also should work in all browsers.

### CODE REVIEW

**Comment by tbushman** [comment]
I could add a test ensuring the img parent doesn't extend beyond the window. That would be a case that wouldn't pass this test.

**Comment by no-stack-dub-sack** [comment]
@tbushman Nice! This is a good simplification, but I might make the `approximately` number 11 again. I can't remember exactly why, but it was changed to that for a specific reason, so the extra leeway was needed in some circumstances.

**Comment by tbushman** [comment]
@no-stack-dub-sack Thanks! And I've noticed this also allows parent div to extend beyond window after all. getBoundingClientRect(). Please wait a moment while I see if I need absolute value.

**Comment by tbushman** [comment]
OK. This should be good to merge.

**Comment by tbushman** [comment]
@tchaffee @no-stack-dub-sack ... merge request pending

**Comment by tchaffee** [comment]
@tbushman Thanks for merging this per our discussion.

**Pull request merged**
