### PR TITLE
Fix/build survey form

### PR DESCRIPTION
**Pull request by AshNaz87**
#### Pre-Submission Checklist

- [x] Your pull request targets the `master` branch of freeCodeCamp/testable-projects-fcc
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] Your changes have been tested either locally or using a newly created CDN based on your fork's testable-projects-fcc/build/bundle.js file

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
  
- [x] Closes currently open issue: Related to https://github.com/freeCodeCamp/freeCodeCamp/issues/37961 in the main fCC repo

#### Description

Check that `for` attributes are present in `label` elements and then check that they are not empty

### CODE REVIEW

**Comment by tbushman** [comment]
Thank you @AshNaz87 for enforcing accessibility in this project with well-formed tests.  
@RandellDawson I think this is important. In my understanding, the 'for' attribute helps screen readers. Can we coordinate this change with the curriculum?

**Comment by AshNaz87** [comment]
Hi @tbushman 

There has been a PR for this in the website repo

@RandellDawson Please take a look

**Comment by lasjorg** [comment]
@AshNaz87 @tbushman

If we want a new user story requirement for explicitly associated label/input I would suggest we only do it for the first three inputs (name, email, age):

1. Simply checking that all label elements have a `for` attribute is not meaningful without knowing that the input elements are correctly associated with the labels. The only way to do this is to use inputs that are part of the requirements and have known ids. 

2. The changes made to the HTML in this PR is not correct and is not how the [for attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label#attr-for) works. It must match the id on the associated input element and all ids must be unique. This again is another reason for only doing it on the first three inputs so we do not have to add new ids to all the inputs and test them all.

3. The current example project would not need to be updated and would pass the new test as it already has explicitly associated labels for the first three inputs. It does _not_ have explicitly associated labels for _all_ inputs, only the first three. The rest are using implicitly associated labels.

4. I would suggest adding the new user story and test after user story/test number 10 (labels test). That seems like the most appropriate place for it.

Technically, I don't think we would need more than this for the test:
```
it('I can see <label> elements with the correct "for" attributes.', function() {
  assert.isNotNull(
    document.querySelector("label[for='name']"),
    'There should be a label element with the "for" attribute set to "name" '
  );

  assert.isNotNull(
    document.querySelector("label[for='email']"),
    'There should be a label element with the "for" attribute set to "email" '
  );

  assert.isNotNull(
    document.querySelector("label[for='number']"),
    'There should be a label element with the "for" attribute set to "number" '
  );
});
```

We can also be more explicit about it and get the labels by id and check that each of them has the correct `for` attribute value. I'm not sure it makes a huge difference but it will make the assert messages a bit more descriptive:
```
it('I can see <label> elements with the correct "for" attributes.', function() {
  assert.strictEqual(
    document.querySelector('#name-label').htmlFor === 'name',
    true,
    'The label with "id=name-label" should have a "for" attribute set to "name" '
  );

  assert.strictEqual(
    document.querySelector('#email-label').htmlFor === 'email',
    true,
    'The label with "id=email-label" should have a "for" attribute set to "email" '
  );

  assert.strictEqual(
    document.querySelector('#number-label').htmlFor === 'number',
    true,
    'The label with "id=number-label" should have a "for" attribute set to "number" '
  );
});
```

Here is an example of how the new User Story might be written:

**User Story `#11`:** The labels with the ids: `id="name-label"`, `id="email-label"`, and `id="number-label"` should each have a `for` attribute with the value set to match the id of the corresponding input element.

**Comment by AshNaz87** [comment]
@lasjorg Noted. Will work on this

**Comment by raisedadead** [comment]
Hey @moT01 can we take a quick look at the current PR and see if adds value as is?

**Comment by moT01** [comment]
Sorry for the long delay here @AshNaz87. The test itself looks good. However, we want to try and avoid adding new tests unless necessary to avoid breaking previously submitted projects. Thanks for your willingness to contribute. If anyone disagrees and thinks we should add this test, feel free to leave a comment and we can reopen this. Thanks and happy coding 🎉

**Pull request closed without merging**
