### PR TITLE
fix: remove bonus requirement from Markdown Previewer

### LINKED ISSUE #305: [UX] Markdown Previewer Optional Challenge (#7)
#### Issue Description
Unit Tests/#Test text (reproduced on the [Beta challenge waypoint here] states that:
>7. OPTIONAL BONUS (you do not need to make this test pass): When I click a link rendered by my markdown previewer, the link is opened up in a new tab (HINT: read the Marked.js docs for this one!)
>8. OPTIONAL BONUS (you do not need to make this test pass): My markdown previewer interprets carriage returns and renders them as <br> (line break) elements

**Problem:** The `marked.js` documentation *is actually necessary for Test #8* (line break behavior). [The link to the relevant page here](https://github.com/markedjs/marked/blob/master/docs/USING_ADVANCED.md#options) is easily found from their github page. **However**, the Optional test #7 isn't an option I was able to find, nor is it strictly speaking necessary.

It is possible that I missed it, but **I dove deep**: I read the documentation at a superficial level, and at a deep one, even reading the link sections of the gfm and commonmark specifications, the source code of marked.js, and browsing closed issues on their github, which is where I found [this comment created just *YESTERDAY, Apr 20 2018* ](https://github.com/markedjs/marked/issues/655) in which the author shows how to not lose the input sanitization of marked, but rather, to add on top of it. I tried to implement it within my react class, and failed, since ES6 classes don't seem to support class properties, just member functions. At some point, I realized that I could probably just use string.replace() to modify the output, and that worked. Without rebuilding the whole library, I don't know how I could make marked() itself return links whose target is another tab. Again, while it's possible that I'm just missing something, and I found the experience to be enlightening, since it forced me to explore so much out of the bounds of the curriculum, I think those with a lower frustration tolerance than I have would get discouraged. Thoughts?

#### Your Code / Link to Your Pen
Not relevant, but [here's my project pen](https://codepen.io/vipatron/pen/mLerKW?editors=0010)

### PR DESCRIPTION
**Pull request by tchaffee**
#### Pre-Submission Checklist

- [x] Your pull request targets the `master` branch of freeCodeCamp/testable-projects-fcc
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] Your changes have been tested either locally or using a newly created CDN based on your fork's testable-projects-fcc/build/bundle.js file
- [x] Working changes have been added to the build by running `npm run build`

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.

- [x] Closes currently open issue: Closes #305 

#### Description
Removed one of the bonus requirements because the markedjs docs no longer include the information needed to understand the solution. See the issue for more details.

### CODE REVIEW

**Comment by tbushman** [comment]
LGTM

**Comment by QuincyLarson** [comment]
@tbushman Awesome! Thanks for QA'ing. Could you resolve the conflict and merge this? 

@tchaffee Thanks for fixing this!

**Comment by tbushman** [comment]
@tchaffee Needs to rebase is all. Thanks.

**Comment by tchaffee** [comment]
@tbushman I am merging this since you already reviewed it and I rebased.

**Pull request merged**
