### PR TITLE
fix all indentations and quotes and max-length for calc and bar chart…

### PR DESCRIPTION
**Pull request by no-stack-dub-sack**
#### Pre-Submission Checklist

- [x] Your pull request targets the `master` branch of freeCodeCamp/testable-projects-fcc
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] Your changes have been tested either locally or using a newly created CDN based on your fork's testable-projects-fcc/build/bundle.js file
- [x] Working changes have been added to the build by running `npm run build`

#### Type of Change

- [ ] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [ ] Tested changes locally.
- [ ] Closes currently open issue (replace XXX with an issue no): Closes #XXX

#### Description

@tbushman @tchaffee so this PR fixes the horrendous 4 space spacing in all files (changes to 2 to be in line with FCC style guidelines). Also, looking through FCCs ESLint rules, it looks like they enforce a maximum of 80 chars per line, so this takes 2 files and adheres them to that just to show what it might look like. To get a better look at them, just click the "view" button at the top of the diff for each file - the 2 I changed are the bar chart and calc test files. We don't need to change any of the others for now, but even though it looks a little funny, I think it is cleaner overall. So this is just an example of what we can change the rest to later to conform. It is really tedious, so again, prob not a priority. Let me know what you guys think of this. 

@tbushman's PR should probably be merged first to avoid major merge conflicts.

### CODE REVIEW

**Comment by tbushman** [comment]
I'm fine with going this way, especially for readability. How do template literals look in your editor? What I like about using quotes is that my editor detects whether I'm missing a quote or whatever. Is it time for me to switch editors? Template literals also would allow some cool new capability.

**Comment by no-stack-dub-sack** [comment]
@tbushman the template literals can get kind of funky - it's weird, in some cases if you make a multi-line string like I did here, when you render the string, the spacing, and the muliple lines will be preserved. Like if you go plug this in on https://repl.it/languages/javascript and you'll see in the "console" that it keeps the multiple lines:
```js
const test = `heloooo
I'm a multi-line template litereal
wahoo!`;

console.log(test)
```
But in the case of this project, the stings still appear as they should in the tests. I don't know if this is because of Mocha, or what. But just a heads up if you try to use it elsewhere. 

But yes, the real power of them is the ability to use varibales in your strings in a more powerful way: 
```js
var adjective = 'awesome';
const TEST_STR = `this is some pretty ${adjective} stuff!`;
```

In React, this really comes in handy for conditional props too:
```js 
<Component className={`green plus icon ${isMobile ? 'small' : 'big'}`} />
```

I'm using Atom, and it will also let me know if I didn't close the quote, whether its a normal quote or a back tick. Not by highlighting in red like it will with regular quotes, but you can still see that something is off. 

What editor are you using?

**Comment by tchaffee** [comment]
These changes make the code more readable for me. I only made one comment about the newlines and extra whitespace when using backticks and the string goes over multiple lines, but @no-stack-dub-sack I think you already answered that in the comment above that the strings look ok in the UI?

My big concern is that with so many changes this could cause rebase and merge problems. What do you think about doing this one or two files at a time per PR?

**Comment by tchaffee** [comment]
I think I figured this out. It's the browser removing extra lines and white space.

https://developer.mozilla.org/en-US/docs/Web/CSS/white-space#Values

**Comment by no-stack-dub-sack** [comment]
@tchaffee I'm not seeing the comment you're referring to in your above comment. Can you clarify what you're talking about with the extra white space? 

I have confirmed that the strings look OK in the UI despite them being broken up over multiple lines though. 

And I agree that one or 2 files at a time is the best way to go about this. For now, if we're all in agreement (once we get your comment resolved), I can fix these conflicts and we can merge these in. I also agree that it becomes more readable. 

For now, I can do these in my spare time, but this can also serve as a template for how everything should look in the end.

**Comment by tbushman** [comment]
@no-stack-dub-sack @tchaffee We are in full agreement that these formatting changes are good. We'll be using them in our next PR for the scatterplot test. One possible exception is the template literals, where we'll probably use strings for now. It may be a little more discussion is needed on that.

**Comment by tchaffee** [comment]
@no-stack-dub-sack The reason the strings look ok in the UI is that the browser removes newlines and compacts all white space into one white space character. I don't see any problem at this point using the backticks as a convenience to continue a string over multiple lines. But we just need to be aware that the string *will* have newline characters and extra white space. If we are going to do this then I'll write something up in the project CONTRIBUTION.md to document it and why it works. The other alternative is to just do it the old fashioned way with multiple strings and the `+` sign:

```
const mystr = 'This is a long string ' +
                       'that I want to break up ' +
                       'over several lines';
```

It doesn't matter much to me which we choose, as long as it is consistent. Please note though that if we use backticks we will need to be aware of which strings will be presented in the browser and which will be used somewhere else. If we need a string that will not be used in the browser we will most likely have to use the style above with the plus sign. So there might be mixed styles in one source file if we do need a string that's not displayed in the browser.

**Comment by no-stack-dub-sack** [comment]
@tchaffee cool, yeah - I vote backticks purely due to the aesthetic. I think we probably should only be using them for the Mocha "user stories" and test error messages

**Comment by no-stack-dub-sack** [comment]
see #129

**Pull request closed without merging**
