### PR TITLE
fix(curriculum): D3 Scatter Plot error

### PR DESCRIPTION
**Pull request by ManasMahanand**
#### Pre-Submission Checklist

- [x] Your pull request targets the `master` branch of freeCodeCamp/testable-projects-fcc
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] Your changes have been tested either locally or using a newly created CDN based on your fork's testable-projects-fcc/build/bundle.js file

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.

- [ ] Closes currently open issue: Closes #XXX

#### Description

Issue freeCodeCamp/freeCodeCamp#34259 had been closed, since @scissorsneedfoodtoo had fixed the issue. But now the change made by him has been removed for some reason.

Running tests on [D3 Scatter Plot](https://www.freecodecamp.org/learn/data-visualization/data-visualization-projects/visualize-data-with-a-scatterplot-graph) fails on 6 and 12 for certain timezones. (For example, it fails on IST):

image

The fix is to remove conversion to UTC on line 57.

**I don't know how this PR will update the codepen itself, this PR can be removed and update the codepen directly.**

### CODE REVIEW

**Comment by lasjorg** [comment]
I don't see a previous PR for this fix. It's likely because the fix never got a PR that the code was re-introduced in a later unrelated PR https://github.com/freeCodeCamp/testable-projects-fcc/pull/1082. Not sure what happend with the Codepen (the backup pen doesn't have `Date.UTC`).

I can confirm the test is passing without `Date.UTC`, but for me it is also passing with it and I didn't test the fix with any timezone changes. But I think this PR is fine. So LGTM.

**Comment by lasjorg** [comment]
Not sure if we need two reviews for PRs on this repo or not?

@scissorsneedfoodtoo Can you update the Codepen with the fix?

**Comment by ManasMahanand** [comment]
Thanks @lasjorg. I looked through the history of this file, looks like the fix never made it to this repo? Anyway, hope this merge won't cause any problems because codepen is not consistent with what is being tested with.

**Comment by scissorsneedfoodtoo** [comment]
Hey @ManasMahanand, thank you for catching this submitting this fix. Also, thank you @lasjorg for the quick review and merge.

Not really sure what happened here, but it's possible that after https://github.com/freeCodeCamp/testable-projects-fcc/pull/1082 was merged that I didn't update the project on CodePen properly :facepalm:

About needing two reviews, I don't think it's totally necessary if it's a smaller fix.

I'll go ahead and update the project on CodePen now.

**Comment by ManasMahanand** [comment]
Yes, it seems to be working now!

**Comment by scissorsneedfoodtoo** [comment]
Awesome! Thanks for confirming that and again for the fix @ManasMahanand.

**Pull request merged**
