### PR TITLE
Added ESLint rules

### LINKED ISSUE #120: Include fcc eslint rules in this project.
Should we and how can we best include [freeCodeCamp's JavaScript Style Guide](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/.eslintrc) in this project? 

If we make a copy, then we won't see any updates. But if we don't include it in this project we are missing ESLINT warnings that should be corrected.

@no-stack-dub-sack and @tbushman any ideas are appreciated.

### PR DESCRIPTION
**Pull request by tchaffee**
#### Pre-Submission Checklist

- [x] Your pull request targets the `master` branch of freeCodeCamp/testable-projects-fcc
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] Your changes have been tested either locally or using a newly created CDN based on your fork's testable-projects-fcc/build/bundle.js file
- [x] Working changes have been added to the build by running `npm run build`

#### Type of Change

- [ ] Small bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.

- [x] Closes currently open issue: Closes #120 

#### Description
- File .eslintrc has the rules. These were just copied from the freeCodeCamp main project.
- Updated package.json with the packages needed by ESLint.
- Added a "pretest" script item to package.json. This will automatically be executed before any tests, which means Travis CI will also do the same.

### CODE REVIEW

**Comment by tchaffee** [comment]
@tbushman As soon as PR #237 is merged, this can be unblocked and merged. Yay! We will finally have the ESLint rules as part of the project instead of managing them locally!

**Comment by tchaffee** [comment]
PR #239 also needs to be merged before this one.

**Comment by tbushman** [comment]
@tchaffee Yay indeed. You've conducted an organized orchestration toward this goal. Thanks!

**Comment by tchaffee** [comment]
@tbushman This is ready for review and merge now. If you wanted to have a peek at the Travis CI tests, you see around line 496 that it's running the ESLint checks:

```
> webpack-test@1.0.0 pretest /home/travis/build/freeCodeCamp/testable-projects-fcc
> eslint src/ test/
```

**Comment by tbushman** [comment]
!! glorious !! LGTM

**Pull request merged**
