### PR TITLE
Fix/update projects technical documentation page

### PR DESCRIPTION
**Pull request by lasjorg**
#### Pre-Submission Checklist

- [x] Your pull request targets the `master` branch of freeCodeCamp/testable-projects-fcc
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [ ] Your changes have been tested either locally or using a newly created CDN based on your fork's testable-projects-fcc/build/bundle.js file
- [ ] Working changes have been added to the build by running `npm run build`

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.

- [ ] Closes currently open issue: Closes #XXX

#### Description

1. Changed the HTML to be valid HTML.
2. Changed CSS to make it look the same with the new HTML structure for the nav. Slightly changed the look, giving the nav links a bit more padding and better left-alignment to the nav header.
3. Cleanup CSS and formatting.
4. Ran test yarn mocha -g "createTechnicalDocsPageTests" - passed
5. Commit hook failed the yarn lint part with missing eslint-plugin-prettier
Installed: npm i eslint-plugin-prettier@latest --save-dev
6. Commit hook still failed (more eslint errors), ran the commits with --no-verify (this PR does not touch any js so hopefully it's OK).

Please let me know if I did anything wrong or if anything needs fixing.

### CODE REVIEW

**Comment by ValeraS** [comment]
@lasjorg You should [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) your commits and write a descriptive commit message. Something like: "fix(projects): update HTML and CSS for Technical Documentation project"

**Comment by lasjorg** [comment]
I'm sorry, I wasn't able to get rebase to work and had to update/reinstall git (vim just got stuck) now I just don't know what is going on. I tried to start over and pull down my branch to do the rebase, not sure how to do that correctly. Instead of wasting your time should I just close this PR and make a new one?

By the way:

1. I installed all the eslint dependencies and it's dumping out 10374 errors from files that i have nothing to do with.

2. If i remove "pre-commit": "yarn lint", it still fails with:

husky > commit-msg (node v10.15.0)
⧗   input: fix(projects): update HTML and CSS for Technical Documentation project
k:\web\testable-projects-fcc\node_modules\@commitlint\cli\lib\cli.js:103
	throw err;
	^

TypeError: formatted.join is not a function
    at k:\web\testable-projects-fcc\node_modules\@commitlint\cli\lib\cli.js:153:33
husky > commit-msg hook failed (add --no-verify to bypass)
 
So, I can't seem to commit unless i use --no-verify
 
2. I'd like to point out that the messages from commitlint are pretty confusing if you don't know anything about it, also don't think i saw them until the CI build failed (i guess because i had to use --no-verify, or i got lost in the lint errors and didn't see it).

3. None of this seems super friendly to people new to development, i did a simple PR on the main FCC repo and i didn't have any issues. I'm not complaining here, just pointing it out.

Can someone explain why the commit hook fails?

**Comment by lasjorg** [comment]
If making a new PR is acceptable. This is what i will do, if you don't mind, tell me if the process is correct:

1. Delete the old branch and make sure my master is up-to-date (or i might just start all over).

2. Make a new branch named "fix/projects-technical-documentation-page" (is that name OK?).

3. Make the changes and commit both files at the same time using the commit message you suggested "fix(projects): update HTML and CSS for Technical Documentation project". I would love it if i didn't have to use --no-verify so i can see if i did everything correctly and won't get a CI fail, is there anything i can do to get it to pass the commit hooks?

4. Push the commit and make a PR (and close this PR).

**Comment by ValeraS** [comment]
@lasjorg Try this in root directory of your clone:
clean working directory:
```sh
$ git clean -fdx
```
install dependency:
```sh
$ yarn
```
you'll see something like:
```output
yarn install v1.12.3
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
...
[4/5] Linking dependencies...
[5/5] Building fresh packages...
Done in 441.51s.
```
check lint:
```
$ yarn lint
```
you'll see something like:
```
yarn run v1.12.3
$ eslint ./**/*.js
Done in 10.86s.
```

after this you can squash your commits:
```
git rebase -i HEAD~6
```
in an opened file, change text to:
```
r ce5ae8d Add updated CSS
f 6e9d542 Add updated HTML
#... here other commits
f 9439a0a Merge branch 'fix/update-projects-technical-documentation-page' of ht…
```
save and close.
After it automatically will be opened file with text:
```
Add updated CSS

# some other text
```
change it to:
```
fix(projects): update HTML and CSS for Technical Documentation project

# some other text
```
save and close.

push you changes with the -f flag.

Feel free ask additional questions.

**Comment by ValeraS** [comment]
Provide additional information:
- OS
- yarn version
- full message of the error

Have you tried suggested steps from the beginning?

**Comment by lasjorg** [comment]
OS: Windows 7 x64

yarn version: yarn -v 1.12.3

Error message:

```
$ yarn lint
yarn run v1.12.3
$ eslint ./**/*.js

Oops! Something went wrong! :(

ESLint: 4.19.1.
ESLint couldn't find the plugin "eslint-plugin-prettier". This can happen for a couple different reasons:

1. If ESLint is installed globally, then make sure eslint-plugin-prettier is also installed globally. A globally-installed E
SLint cannot find a locally-installed plugin.

2. If ESLint is installed locally, then it's likely that the plugin isn't installed correctly. Try reinstalling by running t
he following:

    npm i eslint-plugin-prettier@latest --save-dev

If you still can't figure out the problem, please stop by https://gitter.im/eslint/eslint to chat with the team.

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```



Yes i followed your steps one by one, until the error then stopped.

**Comment by ValeraS** [comment]
@lasjorg try to uninstall eslint globally https://github.com/eslint/eslint/issues/10282

**Comment by lasjorg** [comment]
I still get the same error, I'm going to uninstall node and yarn and delete all npm and yarn folders, then reinstall. I will let you know if it helps.

**Comment by ValeraS** [comment]
@lasjorg run `yarn global list | grep eslint` and `npm list -g | grep eslint` and paste an output here.

**Comment by lasjorg** [comment]
Both the commands do not output anything, i used git bash.

**Comment by tbushman** [comment]
@lasjorg If your PR passes CI with eslint-plugin-prettier installed as a devDependency, go ahead and add that. `yarn add eslint-plugin-prettier@latest --save-dev`

**Comment by lasjorg** [comment]
1. OK, I figured it out, I don't understand why this would happen so please let me know.

I installed eslint-plugin-prettier and again when i ran yarn lint i got the same message as before about another missing module 'eslint-config-prettier/react' however this time i actually paid attention to the log. eslint is referencing a .eslintrc file i have in the folder one level up from the project, not the project root.

```
Cannot find module 'eslint-config-prettier/react'
Referenced from: K:\web\.eslintrc
```

I move that file, removed the eslint-plugin-prettier module and the lint process passes. But why is eslint looking at a .eslintrc file in the folder one level up from the project root folder?


2. OK next question, because i don't feel like messing up this rebase again. When i run git `rebase -i HEAD~6` this is the list of commits i get.


```
pick 3b3bb42 fix: projects tests
pick 9268915 fix: add empty callback to pipeline
pick b0ef1ef chore: clean up
pick ab3a996 fix: update documentation
pick 3ffda1c fix: Add updated CSS and HTML
pick cd28c1f fix: Add updated CSS and HTML
pick ce5ae8d Add updated CSS
pick 6e9d542 Add updated HTML
```

I aborted the rebase and ran `git log --oneline`, this is the output.

```
$ git log --oneline
9439a0a (HEAD -> fix/update-projects-technical-documentation-page, origin/fix/update-projects-technical-documentation-page) Merge branch 'fix/update-projects-technical-documentation-page' of https://github.com/lasjorg/testable-projects-fcc into fix/update-projects-technical-documentation-page
3ffda1c fix: Add updated CSS and HTML
0d2f038 fix: Add updated CSS and HTML
cd28c1f fix: Add updated CSS and HTML
6e9d542 Add updated HTML
ce5ae8d Add updated CSS
d93e6b0 (origin/master, origin/HEAD, master) Merge pull request #747 from ValeraS/feat/projects
...more commits
```

So what rebase commands should i run?

I'm really sorry to take up so much of your time, but i want to make sure i get it right. I have only done a rebase one time before and that was just for testing.

Note: As i said, i tried to start over again by pulling down my fork and getting to the branch, I have never done this before and apparently you can't just get to a branch without doing a checkout. I think i did "`git checkout -b fix/update-projects-technical-documentation-page origin/fix/update-projects-technical-documentation-page`", but i really don't remember anymore. So I'm not sure if my local copy is on par with my fork or not.

Again sorry for all the trouble, at least I'm hopefully learning something.

**Comment by ValeraS** [comment]
@lasjorg  on your branch run:
```
git reset d93e6b08 --soft
```
and
```
git commit -m 'here commit message'
```

**Comment by lasjorg** [comment]
Are we good? Please tell me we are good.

@ValeraS 
Thank you so much for all your help and again I apologize, hopefully, I didn't ruin too much of your weekend with this.

**Comment by ValeraS** [comment]
@lasjorg All good! Give us some time and we'll merge it.

**Comment by ValeraS** [comment]
Hi @lasjorg. Congrats on your first pull request (PR)! 🎉

Thank you for your contribution! 👍
We're happy to accept these changes, and look forward to future contributions. 📝

**Pull request merged**
