### PR TITLE
chore(tools): bash deploy.sh without cwd delimiter

### PR DESCRIPTION
**Pull request by tbushman**
#### Pre-Submission Checklist

- [ ] Your pull request targets the `master` branch of freeCodeCamp/testable-projects-fcc
- [ ] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [ ] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [ ] Your changes have been tested either locally or using a newly created CDN based on your fork's testable-projects-fcc/build/bundle.js file
- [ ] Working changes have been added to the build by running `npm run build`

#### Type of Change

- [ ] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [ ] Tested changes locally.

- [ ] Closes currently open issue: Closes #XXX

#### Description

per @ValeraS this should fix the deploy process

### CODE REVIEW

**Comment by tbushman** [comment]
@raisedadead Will you please add @tchaffee as a contributor at fCC/CDN ? It's his credentials pushing our auto-deploy. Thanks!

**Comment by ValeraS** [comment]
@tbushman @tchaffee IMO, beter to distingush this credential.

And if we decide not to change `CDN_USER` and `CDN_API_KEY`, I think we should merge this PR anyway.

**Comment by raisedadead** [comment]
> ...credentials pushing our auto-deploy. 

Hi @tbushman @tchaffee @ValeraS 

Thanks for the update. I just checked that @tchaffee is already having the collaborator on the repo. 

Other than that, I would insist using @camperbot account for generating any credentials that you need. I can have them created for you, when you need them. This workflow is just standard what we use everywhere.

**Comment by tbushman** [comment]
@raisedadead Thanks! Yes, we need both `CDN_USER` and `CDN_API_KEY` created.

**Comment by tbushman** [comment]
@ValeraS I'm merging this to see if it works. If not, I'll open a new issue for the credentials.

**Pull request merged**
