### PR TITLE
fix: use serve-https github repo instead of the broken npm

### PR DESCRIPTION
**Pull request by tchaffee**
#### Pre-Submission Checklist

- [x] Your pull request targets the `master` branch of freeCodeCamp/testable-projects-fcc
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] Your changes have been tested either locally or using a newly created CDN based on your fork's testable-projects-fcc/build/bundle.js file
- [ ] Working changes have been added to the build by running `npm run build`

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.

- [ ] Closes currently open issue: Closes #XXX

#### Description
The npm package for serve-https is currently broken due to some internal issues they are having with servers being down. In the meantime they recommend we use their github repo for the package. 
- Changed package.json to follow their recommendation. If they fix this soon we can revert to using the npm package, and if not we should look for a replacement solution.
- Fixed a bug with the latest version of Chrome (64) that is throwing a security error when we try to check for media queries in the CSS.
- Added a `sleep` to the automated testing because there is a timing problem on CodePen now with iframes.
- Travis CI now requires the '--no-sandbox' flag to be passed to Chrome.

Note that I would have created separate PRs for these, but they all need each other in order for the CI tests to pass. Since they are all small changes, it should be ok to dump them in one PR.

### CODE REVIEW

**Comment by tbushman** [comment]
@tchaffee It looks like this PR could potentially close issue #281 , too ... :)

**Comment by tchaffee** [comment]
Travis CI is getting 'WebDriverError: unknown error: Chrome failed to start: crashed'. I'll look into this as soon as I get a chance.

**Comment by tchaffee** [comment]
@tbushman This is working now, except for the Random Quote Machine which is expected. I'll see if I can fix Random Quote Machine tomorrow so we can get all the tests to pass before merging. But in the meantime you can review the code here to see if that's OK.

**Comment by tbushman** [comment]
LGTM

**Comment by tbushman** [comment]
@tchaffee should I unmerge / revert merge this? Please see the RQM index.js in #282 comments.

**Comment by tchaffee** [comment]
@tbushman I think it's fine to leave it merged.

**Pull request merged**
