### PR TITLE
fix(project): update HTML and CSS

### PR DESCRIPTION
**Pull request by lasjorg**
#### Pre-Submission Checklist

- [x] Your pull request targets the `master` branch of freeCodeCamp/testable-projects-fcc
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] Your changes have been tested either locally or using a newly created CDN based on your fork's testable-projects-fcc/build/bundle.js file
- [x] Working changes have been added to the build by running `npm run build`

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.

- [ ] Closes currently open issue: Closes #XXX

#### Description
The HTML had a few issues I also did some minor tweaks to the CSS.
Tested and validated.

@tbushman I would love an extra set of eyes just to make sure I didn't miss anything.

### CODE REVIEW

**Comment by lasjorg** [comment]
Not sure what is going on, the CI is failing on:
1) Project "Drum Machine" in firefox should pass all tests

**Comment by lasjorg** [comment]
@tbushman @ValeraS 

Can any of you help me figure out the CI error?

When I run the test script locally it passes the test that is failing on the CI. However, Chrome fails all 5 D3 tests (Firefox passes them). If I build the projects and manually run the D3 tests they all pass in Chrome.

Not sure what is causing the CI to fail?

**Comment by tbushman** [comment]
Thanks @lasjorg. I will open an issue and hopefully we can catch up on these PRs. Sorry for the delay. This drum machine error is not related to your code, which looks good!

**Comment by lasjorg** [comment]
I will close this PR. New PR is here https://github.com/freeCodeCamp/testable-projects-fcc/pull/988

**Pull request closed without merging**
