### PR TITLE
fix: ask for help link

### PR DESCRIPTION
**Pull request by naomi-lgbt**
#### Pre-Submission Checklist

- [X] Your pull request targets the `master` branch of freeCodeCamp/testable-projects-fcc
- [X] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [X] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [X] Your changes have been tested either locally or using a newly created CDN based on your fork's testable-projects-fcc/build/bundle.js file

#### Type of Change

- [X] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [X] Tested changes locally.

- [ ] Closes currently open issue: Closes #XXX

#### Description

Change the ask for help link to one that doesn't 404.

### CODE REVIEW

**Review by ShaunSHamilton — APPROVED** [review]
This LGTM 👍 ... I am surprised this did not come up a lot. I suppose few must use this button

**Comment by nhcarrigan** [comment]
I wasn't sure which category to point it to, so I figured `general` was the safest.

**Comment by ShaunSHamilton** [comment]
>  I figured general was the safest.

I was thinking our biggest concern might be i18n - all users get directed to English forum. But, that could easily be brought up in a new issue on the main repo - out of this PR's scope.

**Review by huyenltnguyen — APPROVED** [review]
LGTM as well 👍

**Pull request merged**
