### PR TITLE
Improve webpack, bundle building, and use yarn

### PR DESCRIPTION
**Pull request by tchaffee**
#### Pre-Submission Checklist

- [x] Your pull request targets the `master` branch of freeCodeCamp/testable-projects-fcc
- [ ] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [ ] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [ ] Your changes have been tested either locally or using a newly created CDN based on your fork's testable-projects-fcc/build/bundle.js file
- [ ] Working changes have been added to the build by running `npm run build`

#### Type of Change

- [ ] Small bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.

- [ ] Closes currently open issue: Closes #XXX

#### Description
Improve webpack, bundle building, and use yarn

### CODE REVIEW

**Comment by tchaffee** [comment]
@Bouncey @raisedadead @tbushman Please respond on this new PR instead.

I have this working locally. It was a bug with the ScatterPlot Codepen and that it was storing times in locale format instead of ISO8601, which made the new Date parsing kind of random. I'm surprised it didn't break before this.

Anyway, I was wondering if I should commit `yarn.lock`? If so, I'll add it and then make a squashed commit for review.

**Comment by tbushman** [comment]
I'm in favor of checking in the lock file. Thanks for this.

**Comment by raisedadead** [comment]
@tchaffee yes that is a good idea. And also if you could squash all the commits. Anyways I am hopeful the bundle size will reduce significantly? Do you have any stats? I guess currently it is 1MB of more.

**Comment by tchaffee** [comment]
Commits have been squashed and yarn.lock is included now.

Could everyone listed please take a close look at this PR? Due to the package.json since being updated in a different PR, I had to do some tricky merges and I want to make sure I got everything right. Being unfamiliar with the changes myself I might have missed something.

@raisedadead Yes, the bundle.js used to be about 1.02MB and now it's about 0.5MB.

**Comment by tbushman** [comment]
I'm gonna go ahead and guess the huge size is from https://github.com/freeCodeCamp/testable-projects-fcc/blob/master/src/data/choropleth_map/counties.json  
  
Can we CDN that? Maybe separate PR for that if so...

**Comment by raisedadead** [comment]
> Can we CDN that?

Yes, we should totally create it off under a directory similar to the bundle, on the the CDN repo.

**Comment by tchaffee** [comment]
> Are the beta package inclusions intentional 

I'm pretty sure that's what @Bouncey had there, so maybe he can answer that better than me.

> Yes, we should totally create it off under a directory similar to the bundle, on the the CDN repo.

Can we create a new issue for that please? 

I'm also guessing that as another issue we could improve the build process by no longer committing `bundle.js` and having Travis create it? Something like that? It always creates a problem with merges, and it's not source code. It's part of the build process. Anyone here know best practice about that? I'm just guessing.

**Comment by tchaffee** [comment]
> Can we CDN that?

Nice catch @tbushman

**Comment by tchaffee** [comment]
@Bouncey Just waiting for your review to make sure I did the merges correctly and didn't miss anything from your original PR.

**Comment by raisedadead** [comment]
Hi @tbushman @tchaffee we have gotten a merge conflict to resolve.

**Comment by raisedadead** [comment]
@Bouncey can you approve the changes when you get a minute?

**Comment by Bouncey** [comment]
# LGTM

Thanks @tchaffee :+1:

**Pull request merged**
