### PR TITLE
Feat/projects

### LINKED ISSUE #731: Place testable projects form CodePen into this repo
pros:
- not depend on CodePen (if they change something our tests will be broken)
- quicker and simpler automated tests
- the standard process of changes (through a PR)
- history of changes

/cc @QuincyLarson @tbushman @raisedadead @tchaffee

### PR DESCRIPTION
**Pull request by ValeraS**
#### Pre-Submission Checklist

- [x] Your pull request targets the `master` branch of freeCodeCamp/testable-projects-fcc
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [ ] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] Your changes have been tested either locally or using a newly created CDN based on your fork's testable-projects-fcc/build/bundle.js file
- [ ] Working changes have been added to the build by running `npm run build`

#### Type of Change

- [ ] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.

- [x] Closes currently open issue: Closes #731

### CODE REVIEW

**Comment by tbushman** [comment]
This will be merged without squashing due to orderliness. Sooon.

**Comment by tchaffee** [comment]
In the future would it be possible to get the entire team involved before making such a big change to our overall approach? I was on vacation for a couple of weeks when this PR was merged. And then I just kind of ignored this PR because I wanted to make sure that any concerns I had were valid concerns. And yes a few weeks later I am still bothered by some stuff that happened with this PR.

Moving our code to here as a backup is a good first step. But this PR did a lot more than that.

A few of specific concerns:

1. Our tests now run against code on github. But students still create their projects on CodePen. If CodePen does something that breaks our example code, we won't see that right away. Instead we will have to wait until students get a bad experience with something not working. Until we actually do move away from CodePen, the tests should run over CodePen. This is best practice when it comes to testing. Testing in an environment which is significantly different from production isn't a real test.
1. We added gulp to our set of tools and we should be moving away from gulp. We want to use fewer tools not more and npm should be able to do everything that gulp does by now.
1. We merged without squashing commits. Either our process is broken and should be improved. Or we should stick to our process. I don't know which it is, but it's worth discussing. 

@raisedadead your input would be appreciated here.

**Comment by raisedadead** [comment]
Hi @tchaffee 

IIRC, It was decided on the original issue thread and both me and @QuincyLarson have had spoken with @ValeraS on the direction here.

So, this PR was required to move off of CodePen as a future goal. This PR does that very well.

Now as for your concerns:

> 1. Our tests now run against code on github...

Yes, I agree. The testing has moved off of CodePen as a source of truth, which could have been done over stages, after we moved off of CodePen completely.

CodePen does not have a very efficient way of us being able to control our source from GitHub. We are looking at others like CodeSandbox which do and also even being able to do so ourselves. 

With that in mind, we aren't going to be changing any sources on CodePen, before it is changed here. Only Myself and Quincy have access to the pens to ensure this for now. This does leave us vulnerable if CodePen themselves break something.

So, while this is not ideal and is incomplete, it's much better than our previous workflow, and headed in the right direction.

> 2. We added gulp to our set of tools and we should be moving away from gulp...

This is an opinion so, I'll let @ValeraS @tbushman confirm if it is necessary for our setup or we can potentially simplify the flow. 

Either way, if a tool helps the maintainers, its OK to have it. If it breaks something or becomes a pain point, it is OK to not have it.

> 3. We merged without squashing commits...

Again, an opinion, and here is my take: 

- We do this on projects which are large like freeCodeCamp main and have less chance of making contributors follow conventions. Remember there, more than 90% are doing this for the first time.
- This project can differ however. This PR was excellent, because each commit may be referred to later for the project that it adds. Baring the last couple commits, it's really good in following the convention. 

So, Yes, I would take your opinion on this and enforce conventional commits as a process on this repo. I would also go far as CI check this. We have done this in the past on the curriculum repo and it had been paying off then.

But, the opinion here is each project could be handled differently, depending on the need.

That said, here is what could have been improved on this PR:

1. We should have not moved off the testing right away and could have discussed a bit more.
2. Or, we could have notified the stakeholders a bit more on this change. 

Not the end of the world. But we did learn something.

Thanks a lot @ValeraS for preparing this PR. @tbushman thanks for reviewing and thanks @tchaffee for the feedback. Let's take this for improving our contribution.

Happy contributing!

**Comment by QuincyLarson** [comment]
Thanks @raisedadead for your comprehensive answers to @tchaffee's legitimate concerns about this.

There will always be tradeoffs. I am grateful we had this discussion, and I hope we'll continue to discuss these architecture decisions and their trade-offs going forward.

Thanks to @ValeraS for prepping this and @tbushman for QA'ing it.

**Comment by tchaffee** [comment]
Agreed it's mostly "we did learn something". I'm not looking to reverse the changes. I'm just looking to avoid this in the future. 

The one thing I do want to push back strongly about though is using gulp. I personally don't want to learn gulp. I already have a long list of new stuff I need to learn for the FCC project.  And this repo already has a steep enough learning curve. My long term goal is to continue to reduce the number of tools we use, and to reduce the learning curve for new contributors. I hope we can all align on that goal, and just use npm instead of gulp. @ValeraS might be the best one to say how easy or difficult that might be, since he wrote the gulp stuff.

**Comment by tchaffee** [comment]
Worth adding that my resistance to adding new dependencies isn't coming out of thin air. It has long been a part of our contributing guide:

> Dependencies
> 
> Much like the project tests, we use Mocha and Chai. For automating the browser we also use Selenium, chromedriver, geckodriver, webpack-dev-server and live-server. Please be cautious about adding new dependencies unless absolutely needed. 

https://github.com/freeCodeCamp/testable-projects-fcc/blob/master/CONTRIBUTING.md#dependencies

**Comment by tchaffee** [comment]
And just to keep things in perspective, I agree with everyone that overall this is a good contribution that moves the project forward. Thanks to both @ValeraS and @tbushman for a job well done.

**Comment by ValeraS** [comment]
@tchaffe I don't know how to replace gulp by npm. Gulp is a build system, npm is a package manager. They are solve different tasks. Can you give me a hint how to do this, please?

**Comment by raisedadead** [comment]
I think what @tchaffee means is we could use `npm run-script` command for our tasks. I have been a strong advocate of this. We have been using a lot of this in the main repository.

Our commands on main repository are intuitive:

```
npm run develop
npm run seed
npm run clean
```

Here is an article that inspired me then: https://deliciousbrains.com/npm-build-script/
You can chain, write node scripts to do complex tasks like linting, and then use them in a run-script.
There are modules like `npm-run-all` that we can use to do things concurrently, and more.

**Comment by raisedadead** [comment]
We used to have a `npm run commit` as well. Which I would love to add to all repos, with our convention.

**Comment by tchaffee** [comment]
@ValeraS here is an article that was published by freeCodeCamp itself. There are actually lots of these articles out there:

https://medium.freecodecamp.org/why-i-left-gulp-and-grunt-for-npm-scripts-3d6853dd22b8

**Comment by tchaffee** [comment]
Didn't read this one, but it's just another example of how many there are. I hope it helps. I can get more involved with specific questions in a few days if that's needed.

https://www.keithcirkel.co.uk/how-to-use-npm-as-a-build-tool/

**Comment by tbushman** [comment]
The gulp file is compiling a lot of disparate inputs, iteratively from a list of directories. If someone can make a webpack config that will do the same work, then maybe we can discuss that, but `npm run-scripts` by itself isn't an analogue for what gulpfile.js is doing. Seems like, to get the same functionality with webpack, there would need to be separate configurations for each project or else a long, multi-faceted configuration or something that might wind up being more complex than the gulpfile.js.

**Comment by ValeraS** [comment]
@raisedadead Could you please look at `package.json` and `gulpfile.js` files and give me advice what can be done?
IMO, gulp here is used like webpack. All you need to working on the project are in npm scripts.

**Comment by raisedadead** [comment]
Okay, Thanks a lot for clarifying.

Let's just stick to Gulp for this project that you guys already are using.

As long as its abstracted and we are documenting the commands in the docs, that a contributor needs to use, I think I am fine with Gulp.

I would not be in favor of switching one tool for another, like webpack unless it adds value. Since @tbushman and @ValeraS have confirmed `run-script` will add complexity. Its best we stick with Gulp.

Unless, @tchaffee you can come up with a more suitable replacement in a PR.

**Comment by tchaffee** [comment]
@raisedadead , @tbushman , @ValeraS 

I would like to try to come up with a replacement. I'm convinced keeping our toolbelt very slim is key to attracting new people to the project. @ValeraS could you document what each part of the gulp script is doing? I am definitely aware that it *might* be the best solution. I just want to double check it because of my goal of making it super easy for new contributors to pitch in. Oh, and it's not just tools. I am constantly looking for opportunities to refactor and delete code. I think @tbushman can testify to that. :-D

**Comment by tbushman** [comment]
@tchaffee Looking over the gulpfile.js, what I like is that you can sort of see what's happening there. There are a lot of think-pieces out there about what tools are best. The gulpfile is functional at funneling compiled SPAs into folders. Maybe open an issue about adding comments, and @ValeraS or another volunteer can get to adding some key notes when possible.

**Pull request merged**
