### PR TITLE
fix: styles - test buttons insufficient contrast ratio failing accessibility audits

### LINKED ISSUE #874: Projects using FCC test suite fail accessibility audits due to insufficient contrast ratio
#### Issue Description

Projects using FCC test suite fail accessibility audits due to insufficient color contrast on the buttons "Run Tests" and "Tests". The following values used to style the buttons in `src/stylesheets/fcc-test-ui.css` are the cause of this issue - 
```
button.fcc_foldout_button {
  background-color: rgba(128, 128, 128, 0.7);
  color: white;
}
```

#### Browser Information

* Browser Name, Version: Chrome Version 73.0.3683.103 (Official Build) (64-bit)
* Operating System: Windows 10 Pro
* Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen

Go to this link - [Markdown Previewer](https://abhishekakade.github.io/markdown-previewer/) and run Audits from Chrome with Accessibility features checked to see the issue.
```
 // this is the suggested fix
button.fcc_foldout_button {
  background-color: rgba(50, 50, 50, 0.75);
  color: white;
}
 
```

#### Screenshot

[fcc-test-suite-accessibility-issue-ss.jpg](https://i.postimg.cc/c4gHdByh/fcc-test-suite-accessibility-issue-min.jpg)

### PR DESCRIPTION
**Pull request by abhishekakade**
#### Pre-Submission Checklist

- [x] Your pull request targets the `master` branch of freeCodeCamp/testable-projects-fcc
- [ ] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] Your changes have been tested either locally or using a newly created CDN based on your fork's testable-projects-fcc/build/bundle.js file
- [ ] Working changes have been added to the build by running `npm run build`

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.

- [x] Closes currently open issue: Closes #874 

#### Description

Changed background-color property for test suite buttons in file `src/stylesheets/fcc-test-ui.css` so that they pass accessibility audits.

Previously - 
```
button.fcc_foldout_button {
  background-color: rgba(128, 128, 128, 0.7);
  color: white;
}
```
Fix - 
```
 // this is the suggested fix
button.fcc_foldout_button {
  background-color: rgba(50, 50, 50, 0.75);
  color: white;
}
```

### CODE REVIEW

**Comment by tbushman** [comment]
@abhishekakade Thanks. You will probably want to change the file, `/src/stylesheets/fcc-test-toggler.css`, too. This is where the dark green bars background-color is set. I'll test it before merging.
```  
.fcc_hamburger {
  ...
  background: darkgreen !important;
  ...
}   
```

**Comment by abhishekakade** [comment]
@tbushman, the accessibility audits only show those 2 buttons (Run Tests & Tests) with insufficient contrast ratio for grayish background (with opacity) and white text on top of it. The `.fcc_hamburger` class div elements have a yellowish background with dark green (div background) color BUT do not have any text in them so I guess it doesn't matter if they have a sufficient contrast or not. I did a quick local test by changing my background color to black and `.fcc_hamburger` element with dark green color did not show up on the accessibility issues.

I also noticed that when the audit was running, the hamburger menu was always open. Perhaps due to the default behavior of FCC Test Suite menu to open automatically? (I don't know much about that). So I thought they only checked contrast ratio on open hamburger menus.

So I did a little test. I ran the audit again and closed the hamburger menu as soon as it opened (during the test). But when I did that, the audits didn't show any contrast ratio problems (which were seen on open hamburger menu form with 'Run Tests' and 'Tests' buttons. Instead it showed another accessibility issue in the FCC Test Suite form. I've attached a link to the screenshot below. That error is from the test selection drop down menu and it says it does not have appropriate labels for screen readers.

[FCC Test Suite Form Accessibility Screenshot](https://i.postimg.cc/QMCsxbqX/fcc-a11y-2.jpg)

So should I raise another issue for changing that file? It's the same file that had `target="_blank" rel="noopener"` issue. Located at `src/utils/fcc-test-suite-skeleton.html`. Please let me know. Thanks!

**Comment by tbushman** [comment]
@abhishekakade Thank you, no. I haven't run your PR, so I mistakenly assumed that was what was failing the test. If it passes the accessibility test then we should leave it. :) Thanks. I'll check and merge this soon.

**Comment by tbushman** [comment]
LGTM! Thanks @abhishekakade !

**Pull request merged**
