### PR TITLE
fix text content overflowing container

### PR DESCRIPTION
**Pull request by alexswiontek**
#### Pre-Submission Checklist

- [x] Your pull request targets the `master` branch of freeCodeCamp/testable-projects-fcc
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] Your changes have been tested either locally or using a newly created CDN based on your fork's testable-projects-fcc/build/bundle.js file
- [x] Working changes have been added to the build by running `npm run build`

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.

- [ ] Closes currently open issue: Closes #XXX

#### Description

The content of the test suite overflows the window when on a smaller sized window (e.g.: mobile). This is simply a css change in the flex implementation.

###### Before
before

###### After
after

### CODE REVIEW

**Comment by tbushman** [comment]
@alexswiontek Thanks. @tchaffee I wasn't sure if the intent was to keep passed tests on one line to fit the test result modal contents in the Travis screenshots.

**Comment by tbushman** [comment]
@alexswiontek Thank you. Could you set your jQuery to 3.2.1 for the build? We should do a separate PR for updating jQuery.

**Comment by tbushman** [comment]
@alexswiontek Or if you wait, we can merge the updates PR first. Thanks.

**Comment by alexswiontek** [comment]
@tbushman I can wait 👍 thanks for the quick response!

**Comment by tchaffee** [comment]
@alexswiontek @tbushman The package updates have been merged so this should be also ready to merge now?

**Pull request merged**
