### PR TITLE
fix: update bug report link

### PR DESCRIPTION
**Pull request by nhcarrigan**
Changes bug report link to main repo

#### Pre-Submission Checklist

- [X] Your pull request targets the `master` branch of freeCodeCamp/testable-projects-fcc
- [X] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [X] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [ ] Your changes have been tested either locally or using a newly created CDN based on your fork's testable-projects-fcc/build/bundle.js file

#### Type of Change

- [X] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [ ] Tested changes locally.

- [ ] Closes currently open issue: Closes #XXX

#### Description

Updates the "Report Bug" link to take campers to the freeCodeCamp repository.

### CODE REVIEW

**Review by raisedadead — APPROVED** [review]

**Comment by moT01** [comment]
Did we not want to get rid of this button?

**Comment by raisedadead** [comment]
Yep, if it becomes too noisy. Maybe a good idea to point to the RSA or something similar.

**Comment by moT01** [comment]
Screen Shot 2020-09-25 at 9 39 58 AM
The ask for help button takes you to the forum.

**Comment by raisedadead** [comment]
Cool, we should drop the 'report bug' link in that case and center align the 'ask for help' option

**Comment by nhcarrigan** [comment]
I can look in to this today 😁

**Pull request merged**
