### PR TITLE
fix: assert time-left is formatted correctly

### LINKED ISSUE #755: Suite is missing a test for a pomodoro clock edge case
#### Issue Description

There is an edge case for the pomodoro clock project that is not covered by the test suite.

"When I first click the element with id="start_stop", the
      timer should begin running from the value currently displayed in
      id="session-length", even if the value has been incremented or
      decremented from the original value of 25."

If the session length is set to 60, it is expected that the timer is displaying a value of "60:00", but this case is not covered by the test mentioned above - or any other test.

Following is a link to a live implementation of a project highlighting the issue. You will notice that all the tests pass, though there is actually a bug where the session length is set to 60, while the timer is displaying a value of "00:00" (also reflected in the screenshot below).

https://abdusabri.github.io/fcc-pomodoro-bug/

#### Screenshot

image

#### Suggested fix
If you agree that this case should be covered by the test suite, here is an idea for a suggested fix. If so, i could clean it up and create a proper pull request.

```javascript
it(`When I first click the element with id="start_stop", the
      timer should begin running from the value currently displayed in
      id="session-length", even if the value has been incremented or
      decremented from the original value of 25.`,
      function() {
        clickButtonsById([startStop]);
        assert.strictEqual(
          getMinutes(
            document.getElementById('time-left').innerText
          ),
          getInputValue(document.getElementById('session-length'))
        );
  
        /*****************/
        /* suggested fix */
        resetTimer();
        clickButtonsById(Array(35).fill(seshPlus)); // Set session length to 60
        
        clickButtonsById([startStop]);
  
        // Another option could be to explicitly test for '60' and '60:00' 
        assert.strictEqual(
          getMinutes(
            document.getElementById('time-left').innerText
          ),
          getInputValue(document.getElementById('session-length'))
        );
        /*****************/
      });
```

### PR DESCRIPTION
**Pull request by abdusabri**
#### Pre-Submission Checklist

- [x] Your pull request targets the `master` branch of freeCodeCamp/testable-projects-fcc
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] Your changes have been tested either locally or using a newly created CDN based on your fork's testable-projects-fcc/build/bundle.js file
- [ ] Working changes have been added to the build by running `npm run build`

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.

- [x] Closes currently open issue: Closes #755 

#### Description

This PR fixes an assertion issue for the pomodoro clock testing project. The issue was that all tests pass even if the `time-left` was incorrectly formatted as `00:00` instead of `60:00` when session length is set to `60`

The following screenshots demonstrate the fix

image

image

An example project _before_ the fix can be found here: https://abdusabri.github.io/fcc-pomodoro-bug/
An example project _after_ the fix can be found here: https://abdusabri.github.io/fcc-pomodoro-fix/

### CODE REVIEW

**Comment by tbushman** [comment]
@abdusabri I was trying both the links you posted, and noticed the tests pass for both. Did you update the first link listed above?

**Comment by abdusabri** [comment]
Thanks for checking @tbushman 

I didn't change either of the links

https://abdusabri.github.io/fcc-pomodoro-bug/ -> uses the CDN version of the tests, and all tests pass

https://abdusabri.github.io/fcc-pomodoro-fix/ -> uses a production build of this PR's tests, and one test fails (screenshots in this PR's description)

Would it help if i send a few screenshots comparing them (showing the urls and more details)?

**Comment by tbushman** [comment]
@abdusabri Mainly I checked the first link, expecting it to fail. Sorry. I think we're probably good. Thanks for your patience.

**Comment by abdusabri** [comment]
@tbushman No worries! 🙂  and thanks for reviewing!

**Comment by tbushman** [comment]
@abdusabri I noticed we're using a RegExp on line 83. I think it would be safest to emulate that style of assertion.

**Comment by abdusabri** [comment]
@tbushman Thanks for the feedback

I've updated the code to use `getMinutes` function, which uses the `RegExp`, and I've rebased and squashed the commits.

**Comment by tbushman** [comment]
Alrighty, @abdusabri ! Thanks for your contribution. Congratulations on your first contribution to this repository. LGTM!

**Pull request merged**
