### PR TITLE
Fixed li issue in regexp for Markdown Previewer

### LINKED ISSUE #267: Markdown Previewer list item test fails when using a * (asterisk) or + (plus sign) as a list marker
#### Issue Description

When using either asterisk, plus sign or a minus sign to mark a list item, it gets correctly interpreted as \<li>  in the rendered html.

However, tests are failing on asterisk and plus signs. They are passing as expected on a minus.

If you guys confirm this is a bug, I would love to work on a fix. This would be my first contribution to open  source   :smile_cat: 

#### Your Code / Link to Your Pen

I believe the issue with the regexp in  

```
assert.notStrictEqual(
          markdown.search(/(?:-|\d\.)\s[^|\s-*].+/),
          -1,
          'write some markdown representing an <li> item '
        );
```
in markdown-previewer-tests.js 

Here are the pens.
First two below are to the pens that are failing. ( using  * and + as a list item marker ) 
Last one is to the pen that is passing ( using - as an list item marker )

```
https://codepen.io/irinabrennen/pen/PEPZXj/
Markdown - Failed(*)

https://codepen.io/irinabrennen/pen/wpgpNR
Markdown - Failed(+)

https://codepen.io/irinabrennen/pen/rpjpEe
Markdown - Pass(-)
 
 ```

#### Screenshot

Write some markdown representing an \<li> item test is failing with an asterisk:

image

### PR DESCRIPTION
**Pull request by iabrenne**
#### Pre-Submission Checklist

- [x] Your pull request targets the `master` branch of freeCodeCamp/testable-projects-fcc
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] Your changes have been tested either locally or using a newly created CDN based on your fork's testable-projects-fcc/build/bundle.js file
- [x] Working changes have been added to the build by running `npm run build`

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.

- [x] Closes currently open issue: Closes #267 

#### Description

Updated regexp to allow string representing a list item to begin with either minus sign, plus sign or an asterisk. Previously, only minus sign was allowed.

### CODE REVIEW

**Comment by iabrenne** [comment]
Done! Hope it's OK that there are two commits now.  I am not sure how to combine them :smiley:

**Comment by tbushman** [comment]
You can refer to this guide https://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231 to 'squash' commits into one. :)

**Comment by iabrenne** [comment]
@tbushman Thanks for the guide! I think the two commits are squashed now.

**Comment by tbushman** [comment]
@iabrenne Awesome! I'll merge this and your change will be incorporated into the test suite! Thanks so much for catching the error.

**Comment by iabrenne** [comment]
Yay, my first contribution to open source :) Exciting! :+1:  Thank you for all the guidance!

**Pull request merged**
