### PR TITLE
fix: 25 + 5 Clock

### PR DESCRIPTION
**Pull request by RandellDawson**
#### Pre-Submission Checklist

- [x] Your pull request targets the `master` branch of freeCodeCamp/testable-projects-fcc
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [ ] Your changes have been tested either locally or using a newly created CDN based on your fork's testable-projects-fcc/build/bundle.js file

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [ ] Tested changes locally.

- [ ] Closes currently open issue: Closes #XXX

#### Description

@moT01 @scissorsneedfoodtoo @raisedadead @ojeytonwilliams Read about this PR in the team chat.

### CODE REVIEW

**Review by ojeytonwilliams — APPROVED** [review]
LGTM

**Comment by raisedadead** [comment]
This preview bundle is available at:

https://5f55da18a5b0b7000821f849--freecodecamp-cdn.netlify.app/testable-projects-fcc/v1/bundle.js\

If you want to test it, before make it live.

**Comment by nhcarrigan** [comment]
Ran the preview on my existing clock project and had no issue with the tests still passing :)

**Comment by QuincyLarson** [comment]
Well done, @RandellDawson .

And thanks for the assist, @nhcarrigan @raisedadead @ojeytonwilliams.

**Pull request merged**
